export default {
    selections: {
        to: [
            { id: 'AF', name: 'Afghanistan' },
            { id: 'africa', name: 'Africa, regional' },
            { id: 'AL', name: 'Albania' },
            { id: 'DZ', name: 'Algeria' },
            { id: 'america', name: 'America, regional' },
            { id: 'AO', name: 'Angola' },
            { id: 'AI', name: 'Anguilla' },
            { id: 'AG', name: 'Antigua & Barbuda' },
            { id: 'AR', name: 'Argentina' },
            { id: 'AM', name: 'Armenia' },
            { id: 'asia', name: 'Asia, regional' },
            { id: 'AZ', name: 'Azerbaijan' },
            { id: 'BH', name: 'Bahrain' },
            { id: 'BD', name: 'Bangladesh' },
            { id: 'BB', name: 'Barbados' },
            { id: 'BY', name: 'Belarus' },
            { id: 'BZ', name: 'Belize' },
            { id: 'BJ', name: 'Benin' },
            { id: 'BT', name: 'Bhutan' },
            { id: 'bilateral-unspecified', name: 'Bilateral, unspecified' },
            { id: 'BO', name: 'Bolivia' },
            { id: 'BA', name: 'Bosnia & Herzegovina' },
            { id: 'BW', name: 'Botswana' },
            { id: 'BR', name: 'Brazil' },
            { id: 'BF', name: 'Burkina Faso' },
            { id: 'BI', name: 'Burundi' },
            { id: 'KH', name: 'Cambodia' },
            { id: 'CM', name: 'Cameroon' },
            { id: 'CV', name: 'Cape Verde' },
            { id: 'CF', name: 'CAR' },
            { id: 'central-asia', name: 'Central Asia, regional' },
            { id: 'TD', name: 'Chad' },
            { id: 'CL', name: 'Chile' },
            { id: 'CN', name: 'China' },
            { id: 'CO', name: 'Colombia' },
            { id: 'KM', name: 'Comoros' },
            { id: 'CG', name: 'Congo' },
            { id: 'CD', name: 'DRC' },
            { id: 'CK', name: 'Cook Islands' },
            { id: 'CR', name: 'Costa Rica' },
            { id: 'CI', name: "Côte d'Ivoire" },
            { id: 'country-unspecified', name: 'Country not specified' },
            { id: 'CU', name: 'Cuba' },
            { id: 'DJ', name: 'Djibouti' },
            { id: 'DM', name: 'Dominica' },
            { id: 'DO', name: 'Dominican Republic' },
            { id: 'EC', name: 'Ecuador' },
            { id: 'EG', name: 'Egypt' },
            { id: 'SV', name: 'El Salvador' },
            { id: 'GQ', name: 'Equatorial Guinea' },
            { id: 'ER', name: 'Eritrea' },
            { id: 'ET', name: 'Ethiopia' },
            { id: 'europe', name: 'Europe, regional' },
            { id: 'east-asia', name: 'Far East Asia, regional' },
            { id: 'FJ', name: 'Fiji' },
            { id: 'GA', name: 'Gabon' },
            { id: 'GM', name: 'Gambia' },
            { id: 'GE', name: 'Georgia' },
            { id: 'GH', name: 'Ghana' },
            { id: 'GD', name: 'Grenada' },
            { id: 'GT', name: 'Guatemala' },
            { id: 'GN', name: 'Guinea' },
            { id: 'GW', name: 'Guinea-Bissau' },
            { id: 'GY', name: 'Guyana' },
            { id: 'HT', name: 'Haiti' },
            { id: 'HN', name: 'Honduras' },
            { id: 'IN', name: 'India' },
            { id: 'ID', name: 'Indonesia' },
            { id: 'IR', name: 'Iran' },
            { id: 'IQ', name: 'Iraq' },
            { id: 'JM', name: 'Jamaica' },
            { id: 'JO', name: 'Jordan' },
            { id: 'KZ', name: 'Kazakhstan' },
            { id: 'KE', name: 'Kenya' },
            { id: 'KI', name: 'Kiribati' },
            { id: 'KP', name: 'North Korea' },
            { id: 'XK', name: 'Kosovo' },
            { id: 'KG', name: 'Kyrgyzstan' },
            { id: 'LA', name: 'Lao' },
            { id: 'LB', name: 'Lebanon' },
            { id: 'LS', name: 'Lesotho' },
            { id: 'LR', name: 'Liberia' },
            { id: 'LY', name: 'Libya' },
            { id: 'MK', name: 'Macedonia' },
            { id: 'MG', name: 'Madagascar' },
            { id: 'MW', name: 'Malawi' },
            { id: 'MY', name: 'Malaysia' },
            { id: 'MV', name: 'Maldives' },
            { id: 'ML', name: 'Mali' },
            { id: 'MH', name: 'Marshall Islands' },
            { id: 'MR', name: 'Mauritania' },
            { id: 'MU', name: 'Mauritius' },
            { id: 'YT', name: 'Mayotte' },
            { id: 'MX', name: 'Mexico' },
            { id: 'FM', name: 'Micronesia' },
            { id: 'middle-east', name: 'Middle East, regional' },
            { id: 'MD', name: 'Moldova' },
            { id: 'MN', name: 'Mongolia' },
            { id: 'ME', name: 'Montenegro' },
            { id: 'MS', name: 'Montserrat' },
            { id: 'MA', name: 'Morocco' },
            { id: 'MZ', name: 'Mozambique' },
            { id: 'MM', name: 'Myanmar' },
            { id: 'NA', name: 'Namibia' },
            { id: 'NR', name: 'Nauru' },
            { id: 'NP', name: 'Nepal' },
            { id: 'NI', name: 'Nicaragua' },
            { id: 'NE', name: 'Niger' },
            { id: 'NG', name: 'Nigeria' },
            { id: 'NU', name: 'Niue' },
            {
                id: 'north-central-america',
                name: 'North & Central America, regional'
            },
            { id: 'north-of-sahara', name: 'North of Sahara, regional' },
            { id: 'oceania', name: 'Oceania, regional' },
            { id: 'OM', name: 'Oman' },
            { id: 'PK', name: 'Pakistan' },
            { id: 'PW', name: 'Palau' },
            { id: 'PS', name: 'Palestine' },
            { id: 'PA', name: 'Panama' },
            { id: 'PG', name: 'Papua New Guinea' },
            { id: 'PY', name: 'Paraguay' },
            { id: 'PE', name: 'Peru' },
            { id: 'PH', name: 'Philippines' },
            { id: 'region-unspecified', name: 'Region, unspecified' },
            { id: 'RW', name: 'Rwanda' },
            { id: 'SH', name: 'Saint Helena, Ascension & Tristan da Cunha' },
            { id: 'KN', name: 'Saint Kitts and Nevis' },
            { id: 'LC', name: 'Saint Lucia' },
            { id: 'VC', name: 'Saint Vincent & the Grenadines' },
            { id: 'WS', name: 'Samoa' },
            { id: 'ST', name: 'Sao Tome & Principe' },
            { id: 'SN', name: 'Senegal' },
            { id: 'RS', name: 'Serbia' },
            { id: 'SC', name: 'Seychelles' },
            { id: 'SL', name: 'Sierra Leone' },
            { id: 'SB', name: 'Solomon Islands' },
            { id: 'SO', name: 'Somalia' },
            { id: 'south-central-asia', name: 'South & Central Asia, regional' },
            { id: 'ZA', name: 'South Africa' },
            { id: 'south-america', name: 'South America, regional' },
            { id: 'south-asia', name: 'South Asia, regional' },
            { id: 'south-of-sahara', name: 'South of Sahara, regional' },
            { id: 'SS', name: 'South Sudan' },
            { id: 'LK', name: 'Sri Lanka' },
            { id: 'ex-yugoslavia', name: 'States Ex-Yugoslavia unspecified' },
            { id: 'SD', name: 'Sudan' },
            { id: 'SR', name: 'Suriname' },
            { id: 'SZ', name: 'Swaziland' },
            { id: 'SY', name: 'Syria' },
            { id: 'TJ', name: 'Tajikistan' },
            { id: 'TZ', name: 'Tanzania' },
            { id: 'TH', name: 'Thailand' },
            { id: 'TL', name: 'Timor-Leste' },
            { id: 'TG', name: 'Togo' },
            { id: 'TK', name: 'Tokelau' },
            { id: 'TO', name: 'Tonga' },
            { id: 'TT', name: 'Trinidad & Tobago' },
            { id: 'TN', name: 'Tunisia' },
            { id: 'TR', name: 'Turkey' },
            { id: 'TM', name: 'Turkmenistan' },
            { id: 'TC', name: 'Turks & Caicos Islands' },
            { id: 'TV', name: 'Tuvalu' },
            { id: 'UG', name: 'Uganda' },
            { id: 'UA', name: 'Ukraine' },
            { id: 'UY', name: 'Uruguay' },
            { id: 'UZ', name: 'Uzbekistan' },
            { id: 'VU', name: 'Vanuatu' },
            { id: 'VE', name: 'Venezuela' },
            { id: 'VN', name: 'Viet Nam' },
            { id: 'WF', name: 'Wallis & Futuna' },
            { id: 'west-indies', name: 'West Indies, regional' },
            { id: 'YE', name: 'Yemen' },
            { id: 'ZM', name: 'Zambia' },
            { id: 'ZW', name: 'Zimbabwe' }
        ],
        from: [
            { id: 'adaptation-fund', name: 'Adaptation Fund' },
            { id: 'afdb', name: 'African Development Bank (AfDB)' },
            { id: 'afdf', name: 'African Development Fund (AfDF)' },
            {
                id: 'badea',
                name: 'Arab Bank for Economic Development in Africa (BADEA)'
            },
            { id: 'arab-fund-afesd', name: 'Arab Fund (AFESD)' },
            { id: 'asdb-special-funds', name: 'ADB Special Funds' },
            { id: 'asdb', name: 'Asian Development Bank (ADB)' },
            { id: 'AU', name: 'Australia' },
            { id: 'AT', name: 'Austria' },
            { id: 'BE', name: 'Belgium' },
            { id: 'BG', name: 'Bulgaria' },
            { id: 'CA', name: 'Canada' },
            { id: 'cardb', name: 'Caribbean Development Bank (CarDB)' },
            { id: 'cif', name: 'Climate Investment Funds (CIF)' },
            { id: 'ceb', name: 'Council of Europe Development Bank (CEB)' },
            { id: 'HR', name: 'Croatia' },
            { id: 'CY', name: 'Cyprus' },
            { id: 'CZ', name: 'Czech Republic' },
            { id: 'DK', name: 'Denmark' },
            { id: 'EE', name: 'Estonia' },
            {
                id: 'ebrd',
                name: 'European Bank for Reconstruction and Development (EBRD)'
            },
            { id: 'EU', name: 'European Union' },
            { id: 'FI', name: 'Finland' },
            { id: 'fao', name: 'Food and Agriculture Organisation (FAO)' },
            { id: 'FR', name: 'France' },
            { id: 'DE', name: 'Germany' },
            {
                id: 'gavi',
                name: 'Global Alliance for Vaccines and Immunization (GAVI)'
            },
            { id: 'gef', name: 'Global Environment Facility (GEF)' },
            { id: 'global-fund', name: 'Global Fund' },
            { id: 'gggi', name: 'Global Green Growth Institute (GGGI)' },
            { id: 'GR', name: 'Greece' },
            { id: 'HU', name: 'Hungary' },
            { id: 'IS', name: 'Iceland' },
            { id: 'idb-special-fund', name: 'IDB Special Fund' },
            {
                id: 'imf-concessional-trust-funds',
                name: 'IMF Concessional Trust Funds'
            },
            { id: 'idb', name: 'Inter-American Development Bank (IDB)' },
            { id: 'iaea', name: 'International Atomic Energy Agency (IAEA)' },
            {
                id: 'ibrd',
                name: 'International Bank for Reconstruction and Development (IBRD)'
            },
            { id: 'ida', name: 'International Development Association (IDA)' },
            { id: 'ifc', name: 'International Finance Corporation (IFC)' },
            {
                id: 'ifad',
                name: 'International Fund for Agricultural Development (IFAD)'
            },
            {
                id: 'international-labour-organisation',
                name: 'International Labour Organisation (ILO)'
            },
            { id: 'imf', name: 'International Monetary Fund (IMF)' },
            { id: 'IE', name: 'Ireland' },
            { id: 'islamic-dev-bank', name: 'Islamic Development Bank (IsDB)' },
            { id: 'IL', name: 'Israel' },
            { id: 'IT', name: 'Italy' },
            { id: 'JP', name: 'Japan' },
            {
                id: 'unaids',
                name: 'Joint United Nations Programme on HIV/AIDS (UNAIDS)'
            },
            { id: 'KZ', name: 'Kazakhstan' },
            { id: 'KR', name: 'Korea' },
            { id: 'KW', name: 'Kuwait' },
            { id: 'LV', name: 'Latvia' },
            { id: 'LI', name: 'Liechtenstein' },
            { id: 'LT', name: 'Lithuania' },
            { id: 'LU', name: 'Luxembourg' },
            { id: 'MT', name: 'Malta' },
            { id: 'montreal-protocol', name: 'Montreal Protocol' },
            { id: 'NL', name: 'Netherlands' },
            { id: 'NZ', name: 'New Zealand' },
            { id: 'nordic-dev-fund', name: 'Nordic Development Fund (NDF)' },
            { id: 'NO', name: 'Norway' },
            { id: 'ofid', name: 'OPEC Fund for International Development (OFID)' },
            {
                id: 'osce',
                name: 'Organization for Security and Co-operation in Europe (OSCE)'
            },
            { id: 'PL', name: 'Poland' },
            { id: 'PT', name: 'Portugal' },
            { id: 'RO', name: 'Romania' },
            { id: 'RU', name: 'Russian Federation' },
            { id: 'SA', name: 'Saudi Arabia' },
            { id: 'SK', name: 'Slovak Republic' },
            { id: 'SI', name: 'Slovenia' },
            { id: 'ES', name: 'Spain' },
            { id: 'SE', name: 'Sweden' },
            { id: 'CH', name: 'Switzerland' },
            { id: 'TW', name: 'Taiwan' },
            { id: 'TH', name: 'Thailand' },
            { id: 'TL', name: 'Timor-Leste' },
            { id: 'TR', name: 'Turkey' },
            { id: 'GB', name: 'United Kingdom' },
            { id: 'un-agencies', name: 'UN Agencies' },
            { id: 'AE', name: 'UAE' },
            { id: 'unicef', name: "United Nations Children's Fund (UNICEF)" },
            { id: 'undp', name: 'United Nations Development Programme (UNDP)' },
            {
                id: 'unece',
                name: 'United Nations Economic Commission for Europe (UNECE)'
            },
            { id: 'unep', name: 'United Nations Environment Programme (UNEP)' },
            {
                id: 'unhcr',
                name: 'United Nations High Commissioner for Refugees (UNHCR)'
            },
            { id: 'unpbf', name: 'United Nations Peacebuilding Fund (UNPBF)' },
            { id: 'unfpa', name: 'United Nations Population Fund (UNFPA)' },
            {
                id: 'unta',
                name: 'United Nations Regular Programme for Technical Assistance (UNTA)'
            },
            { id: 'unrwa', name: 'United Nations Relief and Works Agency (UNRWA)' },
            { id: 'US', name: 'United States' },
            { id: 'wfp', name: 'World Food Programme (WFP)' },
            { id: 'who', name: 'World Health Organization (WHO)' }
        ],
        channels: [
            { id: 'public-sector-unknown', name: 'Public sector (unknown country)' },
            { id: 'public-sector-donor', name: 'Public sector (donor government)' },
            {
                id: 'public-sector-recipient',
                name: 'Public sector (recipient government)'
            },
            { id: 'ngo-unknown', name: 'NGO (unknown country)' },
            { id: 'ngo-donor', name: 'NGO (donor-country based)' },
            { id: 'ngo-recipient', name: 'NGO (recipient-country based)' },
            { id: 'public-private-partnership', name: 'Public private partnership' },
            { id: 'multilateral', name: 'Multilateral' },
            { id: 'other', name: 'Other (private sector, think-tank, etc.)' },
            { id: 'unspecified', name: 'Unspecified' }
        ],
        sectors: [
            {
                id: 'agriculture-and-food-security',
                name: 'Agriculture and food security'
            },
            { id: 'banking-and-business', name: 'Banking and business' },
            { id: 'debt-relief', name: 'Debt relief' },
            { id: 'education', name: 'Education' },
            { id: 'environment', name: 'Environment' },
            { id: 'general-budget-support', name: 'General budget support' },
            { id: 'governance-and-security', name: 'Governance and security' },
            {
                id: 'governance-security-and-civil-society',
                name: 'Governance, security and civil society'
            },
            { id: 'health', name: 'Health' },
            { id: 'humanitarian', name: 'Humanitarian' },
            { id: 'industry-and-trade', name: 'Industry and trade' },
            { id: 'infrastructure', name: 'Infrastructure' },
            { id: 'other', name: 'Other' },
            { id: 'other-social-services', name: 'Other social services' },
            { id: 'water-and-sanitation', name: 'Water and sanitation' },
            { id: 'other-sectors-grouped', name: 'Other sectors (grouped)' }
        ],
        bundles: [
            { id: 'oof-grant', name: 'OOF Grant' },
            { id: 'oof-loan', name: 'OOF Loan' }
        ],
        years: [2015, 2014, 2013, 2012, 2011, 2010, 2009, 2008, 2007, 2006]
    },
    yearTotal: { year: 2015, total: '71.5bn' }
};
