// flow-typed signature: 666b48cc19721a21291d777556f8571a
// flow-typed version: <<STUB>>/next/dynamic_v3.0.1/flow_v0.52.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'next/dynamic'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'next/dynamic' {
  declare module.exports: any;
}
