// flow-typed signature: bddd736c543bf521b833d1e8f57a1ec0
// flow-typed version: <<STUB>>/apollo-fetch_v0.3.0/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'apollo-fetch'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'apollo-fetch' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'apollo-fetch/dist/src/apollo-fetch' {
  declare module.exports: any;
}

declare module 'apollo-fetch/dist/src/index' {
  declare module.exports: any;
}

declare module 'apollo-fetch/dist/src/types' {
  declare module.exports: any;
}

// Filename aliases
declare module 'apollo-fetch/dist/src/apollo-fetch.js' {
  declare module.exports: $Exports<'apollo-fetch/dist/src/apollo-fetch'>;
}
declare module 'apollo-fetch/dist/src/index.js' {
  declare module.exports: $Exports<'apollo-fetch/dist/src/index'>;
}
declare module 'apollo-fetch/dist/src/types.js' {
  declare module.exports: $Exports<'apollo-fetch/dist/src/types'>;
}
