// flow-typed signature: 4a8e97df0b5950b77244f114e4e9728b
// flow-typed version: <<STUB>>/csso_v3.1.1/flow_v0.52.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'csso'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'csso' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'csso/dist/csso-browser' {
  declare module.exports: any;
}

declare module 'csso/lib/clean/Atrule' {
  declare module.exports: any;
}

declare module 'csso/lib/clean/Comment' {
  declare module.exports: any;
}

declare module 'csso/lib/clean/Declaration' {
  declare module.exports: any;
}

declare module 'csso/lib/clean/index' {
  declare module.exports: any;
}

declare module 'csso/lib/clean/Operator' {
  declare module.exports: any;
}

declare module 'csso/lib/clean/Rule' {
  declare module.exports: any;
}

declare module 'csso/lib/clean/TypeSelector' {
  declare module.exports: any;
}

declare module 'csso/lib/clean/WhiteSpace' {
  declare module.exports: any;
}

declare module 'csso/lib/compress' {
  declare module.exports: any;
}

declare module 'csso/lib/index' {
  declare module.exports: any;
}

declare module 'csso/lib/replace/Atrule' {
  declare module.exports: any;
}

declare module 'csso/lib/replace/atrule/keyframes' {
  declare module.exports: any;
}

declare module 'csso/lib/replace/AttributeSelector' {
  declare module.exports: any;
}

declare module 'csso/lib/replace/color' {
  declare module.exports: any;
}

declare module 'csso/lib/replace/Dimension' {
  declare module.exports: any;
}

declare module 'csso/lib/replace/index' {
  declare module.exports: any;
}

declare module 'csso/lib/replace/Number' {
  declare module.exports: any;
}

declare module 'csso/lib/replace/property/background' {
  declare module.exports: any;
}

declare module 'csso/lib/replace/property/border' {
  declare module.exports: any;
}

declare module 'csso/lib/replace/property/font-weight' {
  declare module.exports: any;
}

declare module 'csso/lib/replace/property/font' {
  declare module.exports: any;
}

declare module 'csso/lib/replace/String' {
  declare module.exports: any;
}

declare module 'csso/lib/replace/Url' {
  declare module.exports: any;
}

declare module 'csso/lib/replace/Value' {
  declare module.exports: any;
}

declare module 'csso/lib/restructure/1-initialMergeRuleset' {
  declare module.exports: any;
}

declare module 'csso/lib/restructure/2-mergeAtrule' {
  declare module.exports: any;
}

declare module 'csso/lib/restructure/3-disjoinRuleset' {
  declare module.exports: any;
}

declare module 'csso/lib/restructure/4-restructShorthand' {
  declare module.exports: any;
}

declare module 'csso/lib/restructure/6-restructBlock' {
  declare module.exports: any;
}

declare module 'csso/lib/restructure/7-mergeRuleset' {
  declare module.exports: any;
}

declare module 'csso/lib/restructure/8-restructRuleset' {
  declare module.exports: any;
}

declare module 'csso/lib/restructure/index' {
  declare module.exports: any;
}

declare module 'csso/lib/restructure/prepare/createDeclarationIndexer' {
  declare module.exports: any;
}

declare module 'csso/lib/restructure/prepare/index' {
  declare module.exports: any;
}

declare module 'csso/lib/restructure/prepare/processSelector' {
  declare module.exports: any;
}

declare module 'csso/lib/restructure/prepare/specificity' {
  declare module.exports: any;
}

declare module 'csso/lib/restructure/utils' {
  declare module.exports: any;
}

declare module 'csso/lib/usage' {
  declare module.exports: any;
}

// Filename aliases
declare module 'csso/dist/csso-browser.js' {
  declare module.exports: $Exports<'csso/dist/csso-browser'>;
}
declare module 'csso/lib/clean/Atrule.js' {
  declare module.exports: $Exports<'csso/lib/clean/Atrule'>;
}
declare module 'csso/lib/clean/Comment.js' {
  declare module.exports: $Exports<'csso/lib/clean/Comment'>;
}
declare module 'csso/lib/clean/Declaration.js' {
  declare module.exports: $Exports<'csso/lib/clean/Declaration'>;
}
declare module 'csso/lib/clean/index.js' {
  declare module.exports: $Exports<'csso/lib/clean/index'>;
}
declare module 'csso/lib/clean/Operator.js' {
  declare module.exports: $Exports<'csso/lib/clean/Operator'>;
}
declare module 'csso/lib/clean/Rule.js' {
  declare module.exports: $Exports<'csso/lib/clean/Rule'>;
}
declare module 'csso/lib/clean/TypeSelector.js' {
  declare module.exports: $Exports<'csso/lib/clean/TypeSelector'>;
}
declare module 'csso/lib/clean/WhiteSpace.js' {
  declare module.exports: $Exports<'csso/lib/clean/WhiteSpace'>;
}
declare module 'csso/lib/compress.js' {
  declare module.exports: $Exports<'csso/lib/compress'>;
}
declare module 'csso/lib/index.js' {
  declare module.exports: $Exports<'csso/lib/index'>;
}
declare module 'csso/lib/replace/Atrule.js' {
  declare module.exports: $Exports<'csso/lib/replace/Atrule'>;
}
declare module 'csso/lib/replace/atrule/keyframes.js' {
  declare module.exports: $Exports<'csso/lib/replace/atrule/keyframes'>;
}
declare module 'csso/lib/replace/AttributeSelector.js' {
  declare module.exports: $Exports<'csso/lib/replace/AttributeSelector'>;
}
declare module 'csso/lib/replace/color.js' {
  declare module.exports: $Exports<'csso/lib/replace/color'>;
}
declare module 'csso/lib/replace/Dimension.js' {
  declare module.exports: $Exports<'csso/lib/replace/Dimension'>;
}
declare module 'csso/lib/replace/index.js' {
  declare module.exports: $Exports<'csso/lib/replace/index'>;
}
declare module 'csso/lib/replace/Number.js' {
  declare module.exports: $Exports<'csso/lib/replace/Number'>;
}
declare module 'csso/lib/replace/property/background.js' {
  declare module.exports: $Exports<'csso/lib/replace/property/background'>;
}
declare module 'csso/lib/replace/property/border.js' {
  declare module.exports: $Exports<'csso/lib/replace/property/border'>;
}
declare module 'csso/lib/replace/property/font-weight.js' {
  declare module.exports: $Exports<'csso/lib/replace/property/font-weight'>;
}
declare module 'csso/lib/replace/property/font.js' {
  declare module.exports: $Exports<'csso/lib/replace/property/font'>;
}
declare module 'csso/lib/replace/String.js' {
  declare module.exports: $Exports<'csso/lib/replace/String'>;
}
declare module 'csso/lib/replace/Url.js' {
  declare module.exports: $Exports<'csso/lib/replace/Url'>;
}
declare module 'csso/lib/replace/Value.js' {
  declare module.exports: $Exports<'csso/lib/replace/Value'>;
}
declare module 'csso/lib/restructure/1-initialMergeRuleset.js' {
  declare module.exports: $Exports<'csso/lib/restructure/1-initialMergeRuleset'>;
}
declare module 'csso/lib/restructure/2-mergeAtrule.js' {
  declare module.exports: $Exports<'csso/lib/restructure/2-mergeAtrule'>;
}
declare module 'csso/lib/restructure/3-disjoinRuleset.js' {
  declare module.exports: $Exports<'csso/lib/restructure/3-disjoinRuleset'>;
}
declare module 'csso/lib/restructure/4-restructShorthand.js' {
  declare module.exports: $Exports<'csso/lib/restructure/4-restructShorthand'>;
}
declare module 'csso/lib/restructure/6-restructBlock.js' {
  declare module.exports: $Exports<'csso/lib/restructure/6-restructBlock'>;
}
declare module 'csso/lib/restructure/7-mergeRuleset.js' {
  declare module.exports: $Exports<'csso/lib/restructure/7-mergeRuleset'>;
}
declare module 'csso/lib/restructure/8-restructRuleset.js' {
  declare module.exports: $Exports<'csso/lib/restructure/8-restructRuleset'>;
}
declare module 'csso/lib/restructure/index.js' {
  declare module.exports: $Exports<'csso/lib/restructure/index'>;
}
declare module 'csso/lib/restructure/prepare/createDeclarationIndexer.js' {
  declare module.exports: $Exports<'csso/lib/restructure/prepare/createDeclarationIndexer'>;
}
declare module 'csso/lib/restructure/prepare/index.js' {
  declare module.exports: $Exports<'csso/lib/restructure/prepare/index'>;
}
declare module 'csso/lib/restructure/prepare/processSelector.js' {
  declare module.exports: $Exports<'csso/lib/restructure/prepare/processSelector'>;
}
declare module 'csso/lib/restructure/prepare/specificity.js' {
  declare module.exports: $Exports<'csso/lib/restructure/prepare/specificity'>;
}
declare module 'csso/lib/restructure/utils.js' {
  declare module.exports: $Exports<'csso/lib/restructure/utils'>;
}
declare module 'csso/lib/usage.js' {
  declare module.exports: $Exports<'csso/lib/usage'>;
}
