// flow-typed signature: 9ce0828b80c990a4e0ce16f27c881cc5
// flow-typed version: <<STUB>>/react-apollo_v1.4.8/flow_v0.51.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-apollo'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-apollo' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-apollo/ApolloProvider' {
  declare module.exports: any;
}

declare module 'react-apollo/browser' {
  declare module.exports: any;
}

declare module 'react-apollo/flow-typed/npm/@types/enzyme_vx.x.x' {
  declare module.exports: any;
}

declare module 'react-apollo/flow-typed/npm/@types/graphql_vx.x.x' {
  declare module.exports: any;
}

declare module 'react-apollo/flow-typed/npm/@types/invariant_vx.x.x' {
  declare module.exports: any;
}

declare module 'react-apollo/flow-typed/npm/@types/isomorphic-fetch_vx.x.x' {
  declare module.exports: any;
}

declare module 'react-apollo/flow-typed/npm/@types/jest_vx.x.x' {
  declare module.exports: any;
}

declare module 'react-apollo/flow-typed/npm/@types/lodash_vx.x.x' {
  declare module.exports: any;
}

declare module 'react-apollo/flow-typed/npm/@types/node_vx.x.x' {
  declare module.exports: any;
}

declare module 'react-apollo/flow-typed/npm/@types/object-assign_vx.x.x' {
  declare module.exports: any;
}

declare module 'react-apollo/flow-typed/npm/@types/react_vx.x.x' {
  declare module.exports: any;
}

declare module 'react-apollo/flow-typed/npm/@types/react-addons-test-utils_vx.x.x' {
  declare module.exports: any;
}

declare module 'react-apollo/flow-typed/npm/@types/react-dom_vx.x.x' {
  declare module.exports: any;
}

declare module 'react-apollo/flow-typed/npm/@types/react-redux_vx.x.x' {
  declare module.exports: any;
}

declare module 'react-apollo/flow-typed/npm/@types/redux-form_vx.x.x' {
  declare module.exports: any;
}

declare module 'react-apollo/flow-typed/npm/@types/redux-immutable_vx.x.x' {
  declare module.exports: any;
}

declare module 'react-apollo/flow-typed/npm/@types/sinon_vx.x.x' {
  declare module.exports: any;
}

declare module 'react-apollo/flow-typed/npm/babel-jest_vx.x.x' {
  declare module.exports: any;
}

declare module 'react-apollo/flow-typed/npm/babel-preset-react-native_vx.x.x' {
  declare module.exports: any;
}

declare module 'react-apollo/flow-typed/npm/browserify_vx.x.x' {
  declare module.exports: any;
}

declare module 'react-apollo/flow-typed/npm/bundlesize_vx.x.x' {
  declare module.exports: any;
}

declare module 'react-apollo/flow-typed/npm/cheerio_vx.x.x' {
  declare module.exports: any;
}

declare module 'react-apollo/flow-typed/npm/colors_vx.x.x' {
  declare module.exports: any;
}

declare module 'react-apollo/flow-typed/npm/danger_vx.x.x' {
  declare module.exports: any;
}

declare module 'react-apollo/flow-typed/npm/enzyme_v2.x.x' {
  declare module.exports: any;
}

declare module 'react-apollo/flow-typed/npm/enzyme-to-json_vx.x.x' {
  declare module.exports: any;
}

declare module 'react-apollo/flow-typed/npm/flow-bin_v0.x.x' {
  declare module.exports: any;
}

declare module 'react-apollo/flow-typed/npm/graphql-anywhere_vx.x.x' {
  declare module.exports: any;
}

declare module 'react-apollo/flow-typed/npm/hoist-non-react-statics_vx.x.x' {
  declare module.exports: any;
}

declare module 'react-apollo/flow-typed/npm/invariant_v2.x.x' {
  declare module.exports: any;
}

declare module 'react-apollo/flow-typed/npm/isomorphic-fetch_v2.x.x' {
  declare module.exports: any;
}

declare module 'react-apollo/flow-typed/npm/jest_v19.x.x' {
  declare module.exports: any;
}

declare module 'react-apollo/flow-typed/npm/jest-react-native_vx.x.x' {
  declare module.exports: any;
}

declare module 'react-apollo/flow-typed/npm/jsdom_vx.x.x' {
  declare module.exports: any;
}

declare module 'react-apollo/flow-typed/npm/lint-staged_vx.x.x' {
  declare module.exports: any;
}

declare module 'react-apollo/flow-typed/npm/lodash_v4.x.x' {
  declare module.exports: any;
}

declare module 'react-apollo/flow-typed/npm/lodash.flatten_vx.x.x' {
  declare module.exports: any;
}

declare module 'react-apollo/flow-typed/npm/lodash.isequal_vx.x.x' {
  declare module.exports: any;
}

declare module 'react-apollo/flow-typed/npm/lodash.isobject_vx.x.x' {
  declare module.exports: any;
}

declare module 'react-apollo/flow-typed/npm/lodash.pick_vx.x.x' {
  declare module.exports: any;
}

declare module 'react-apollo/flow-typed/npm/minimist_v1.x.x' {
  declare module.exports: any;
}

declare module 'react-apollo/flow-typed/npm/mobx-react_vx.x.x' {
  declare module.exports: any;
}

declare module 'react-apollo/flow-typed/npm/object-assign_v4.x.x' {
  declare module.exports: any;
}

declare module 'react-apollo/flow-typed/npm/pre-commit_vx.x.x' {
  declare module.exports: any;
}

declare module 'react-apollo/flow-typed/npm/prettier_vx.x.x' {
  declare module.exports: any;
}

declare module 'react-apollo/flow-typed/npm/pretty-bytes_vx.x.x' {
  declare module.exports: any;
}

declare module 'react-apollo/flow-typed/npm/prop-types_v15.x.x' {
  declare module.exports: any;
}

declare module 'react-apollo/flow-typed/npm/react-addons-test-utils_v15.x.x' {
  declare module.exports: any;
}

declare module 'react-apollo/flow-typed/npm/react-redux_v5.x.x' {
  declare module.exports: any;
}

declare module 'react-apollo/flow-typed/npm/react-test-renderer_vx.x.x' {
  declare module.exports: any;
}

declare module 'react-apollo/flow-typed/npm/recompose_vx.x.x' {
  declare module.exports: any;
}

declare module 'react-apollo/flow-typed/npm/redux_vx.x.x' {
  declare module.exports: any;
}

declare module 'react-apollo/flow-typed/npm/redux-form_vx.x.x' {
  declare module.exports: any;
}

declare module 'react-apollo/flow-typed/npm/redux-immutable_vx.x.x' {
  declare module.exports: any;
}

declare module 'react-apollo/flow-typed/npm/redux-loop_v2.2.x' {
  declare module.exports: any;
}

declare module 'react-apollo/flow-typed/npm/rollup_vx.x.x' {
  declare module.exports: any;
}

declare module 'react-apollo/flow-typed/npm/source-map-support_vx.x.x' {
  declare module.exports: any;
}

declare module 'react-apollo/flow-typed/npm/swapi-graphql_vx.x.x' {
  declare module.exports: any;
}

declare module 'react-apollo/flow-typed/npm/travis-weigh-in_vx.x.x' {
  declare module.exports: any;
}

declare module 'react-apollo/flow-typed/npm/tslint_vx.x.x' {
  declare module.exports: any;
}

declare module 'react-apollo/flow-typed/npm/typescript_vx.x.x' {
  declare module.exports: any;
}

declare module 'react-apollo/flow-typed/npm/typescript-require_vx.x.x' {
  declare module.exports: any;
}

declare module 'react-apollo/flow-typed/npm/typings_vx.x.x' {
  declare module.exports: any;
}

declare module 'react-apollo/flow-typed/npm/uglify-js_vx.x.x' {
  declare module.exports: any;
}

declare module 'react-apollo/graphql' {
  declare module.exports: any;
}

declare module 'react-apollo/parser' {
  declare module.exports: any;
}

declare module 'react-apollo/queryRecycler' {
  declare module.exports: any;
}

declare module 'react-apollo/react-apollo.browser.umd' {
  declare module.exports: any;
}

declare module 'react-apollo/react-apollo.umd' {
  declare module.exports: any;
}

declare module 'react-apollo/server' {
  declare module.exports: any;
}

declare module 'react-apollo/shallowEqual' {
  declare module.exports: any;
}

declare module 'react-apollo/test-utils' {
  declare module.exports: any;
}

declare module 'react-apollo/types' {
  declare module.exports: any;
}

declare module 'react-apollo/withApollo' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-apollo/ApolloProvider.js' {
  declare module.exports: $Exports<'react-apollo/ApolloProvider'>;
}
declare module 'react-apollo/browser.js' {
  declare module.exports: $Exports<'react-apollo/browser'>;
}
declare module 'react-apollo/flow-typed/npm/@types/enzyme_vx.x.x.js' {
  declare module.exports: $Exports<'react-apollo/flow-typed/npm/@types/enzyme_vx.x.x'>;
}
declare module 'react-apollo/flow-typed/npm/@types/graphql_vx.x.x.js' {
  declare module.exports: $Exports<'react-apollo/flow-typed/npm/@types/graphql_vx.x.x'>;
}
declare module 'react-apollo/flow-typed/npm/@types/invariant_vx.x.x.js' {
  declare module.exports: $Exports<'react-apollo/flow-typed/npm/@types/invariant_vx.x.x'>;
}
declare module 'react-apollo/flow-typed/npm/@types/isomorphic-fetch_vx.x.x.js' {
  declare module.exports: $Exports<'react-apollo/flow-typed/npm/@types/isomorphic-fetch_vx.x.x'>;
}
declare module 'react-apollo/flow-typed/npm/@types/jest_vx.x.x.js' {
  declare module.exports: $Exports<'react-apollo/flow-typed/npm/@types/jest_vx.x.x'>;
}
declare module 'react-apollo/flow-typed/npm/@types/lodash_vx.x.x.js' {
  declare module.exports: $Exports<'react-apollo/flow-typed/npm/@types/lodash_vx.x.x'>;
}
declare module 'react-apollo/flow-typed/npm/@types/node_vx.x.x.js' {
  declare module.exports: $Exports<'react-apollo/flow-typed/npm/@types/node_vx.x.x'>;
}
declare module 'react-apollo/flow-typed/npm/@types/object-assign_vx.x.x.js' {
  declare module.exports: $Exports<'react-apollo/flow-typed/npm/@types/object-assign_vx.x.x'>;
}
declare module 'react-apollo/flow-typed/npm/@types/react_vx.x.x.js' {
  declare module.exports: $Exports<'react-apollo/flow-typed/npm/@types/react_vx.x.x'>;
}
declare module 'react-apollo/flow-typed/npm/@types/react-addons-test-utils_vx.x.x.js' {
  declare module.exports: $Exports<'react-apollo/flow-typed/npm/@types/react-addons-test-utils_vx.x.x'>;
}
declare module 'react-apollo/flow-typed/npm/@types/react-dom_vx.x.x.js' {
  declare module.exports: $Exports<'react-apollo/flow-typed/npm/@types/react-dom_vx.x.x'>;
}
declare module 'react-apollo/flow-typed/npm/@types/react-redux_vx.x.x.js' {
  declare module.exports: $Exports<'react-apollo/flow-typed/npm/@types/react-redux_vx.x.x'>;
}
declare module 'react-apollo/flow-typed/npm/@types/redux-form_vx.x.x.js' {
  declare module.exports: $Exports<'react-apollo/flow-typed/npm/@types/redux-form_vx.x.x'>;
}
declare module 'react-apollo/flow-typed/npm/@types/redux-immutable_vx.x.x.js' {
  declare module.exports: $Exports<'react-apollo/flow-typed/npm/@types/redux-immutable_vx.x.x'>;
}
declare module 'react-apollo/flow-typed/npm/@types/sinon_vx.x.x.js' {
  declare module.exports: $Exports<'react-apollo/flow-typed/npm/@types/sinon_vx.x.x'>;
}
declare module 'react-apollo/flow-typed/npm/babel-jest_vx.x.x.js' {
  declare module.exports: $Exports<'react-apollo/flow-typed/npm/babel-jest_vx.x.x'>;
}
declare module 'react-apollo/flow-typed/npm/babel-preset-react-native_vx.x.x.js' {
  declare module.exports: $Exports<'react-apollo/flow-typed/npm/babel-preset-react-native_vx.x.x'>;
}
declare module 'react-apollo/flow-typed/npm/browserify_vx.x.x.js' {
  declare module.exports: $Exports<'react-apollo/flow-typed/npm/browserify_vx.x.x'>;
}
declare module 'react-apollo/flow-typed/npm/bundlesize_vx.x.x.js' {
  declare module.exports: $Exports<'react-apollo/flow-typed/npm/bundlesize_vx.x.x'>;
}
declare module 'react-apollo/flow-typed/npm/cheerio_vx.x.x.js' {
  declare module.exports: $Exports<'react-apollo/flow-typed/npm/cheerio_vx.x.x'>;
}
declare module 'react-apollo/flow-typed/npm/colors_vx.x.x.js' {
  declare module.exports: $Exports<'react-apollo/flow-typed/npm/colors_vx.x.x'>;
}
declare module 'react-apollo/flow-typed/npm/danger_vx.x.x.js' {
  declare module.exports: $Exports<'react-apollo/flow-typed/npm/danger_vx.x.x'>;
}
declare module 'react-apollo/flow-typed/npm/enzyme_v2.x.x.js' {
  declare module.exports: $Exports<'react-apollo/flow-typed/npm/enzyme_v2.x.x'>;
}
declare module 'react-apollo/flow-typed/npm/enzyme-to-json_vx.x.x.js' {
  declare module.exports: $Exports<'react-apollo/flow-typed/npm/enzyme-to-json_vx.x.x'>;
}
declare module 'react-apollo/flow-typed/npm/flow-bin_v0.x.x.js' {
  declare module.exports: $Exports<'react-apollo/flow-typed/npm/flow-bin_v0.x.x'>;
}
declare module 'react-apollo/flow-typed/npm/graphql-anywhere_vx.x.x.js' {
  declare module.exports: $Exports<'react-apollo/flow-typed/npm/graphql-anywhere_vx.x.x'>;
}
declare module 'react-apollo/flow-typed/npm/hoist-non-react-statics_vx.x.x.js' {
  declare module.exports: $Exports<'react-apollo/flow-typed/npm/hoist-non-react-statics_vx.x.x'>;
}
declare module 'react-apollo/flow-typed/npm/invariant_v2.x.x.js' {
  declare module.exports: $Exports<'react-apollo/flow-typed/npm/invariant_v2.x.x'>;
}
declare module 'react-apollo/flow-typed/npm/isomorphic-fetch_v2.x.x.js' {
  declare module.exports: $Exports<'react-apollo/flow-typed/npm/isomorphic-fetch_v2.x.x'>;
}
declare module 'react-apollo/flow-typed/npm/jest_v19.x.x.js' {
  declare module.exports: $Exports<'react-apollo/flow-typed/npm/jest_v19.x.x'>;
}
declare module 'react-apollo/flow-typed/npm/jest-react-native_vx.x.x.js' {
  declare module.exports: $Exports<'react-apollo/flow-typed/npm/jest-react-native_vx.x.x'>;
}
declare module 'react-apollo/flow-typed/npm/jsdom_vx.x.x.js' {
  declare module.exports: $Exports<'react-apollo/flow-typed/npm/jsdom_vx.x.x'>;
}
declare module 'react-apollo/flow-typed/npm/lint-staged_vx.x.x.js' {
  declare module.exports: $Exports<'react-apollo/flow-typed/npm/lint-staged_vx.x.x'>;
}
declare module 'react-apollo/flow-typed/npm/lodash_v4.x.x.js' {
  declare module.exports: $Exports<'react-apollo/flow-typed/npm/lodash_v4.x.x'>;
}
declare module 'react-apollo/flow-typed/npm/lodash.flatten_vx.x.x.js' {
  declare module.exports: $Exports<'react-apollo/flow-typed/npm/lodash.flatten_vx.x.x'>;
}
declare module 'react-apollo/flow-typed/npm/lodash.isequal_vx.x.x.js' {
  declare module.exports: $Exports<'react-apollo/flow-typed/npm/lodash.isequal_vx.x.x'>;
}
declare module 'react-apollo/flow-typed/npm/lodash.isobject_vx.x.x.js' {
  declare module.exports: $Exports<'react-apollo/flow-typed/npm/lodash.isobject_vx.x.x'>;
}
declare module 'react-apollo/flow-typed/npm/lodash.pick_vx.x.x.js' {
  declare module.exports: $Exports<'react-apollo/flow-typed/npm/lodash.pick_vx.x.x'>;
}
declare module 'react-apollo/flow-typed/npm/minimist_v1.x.x.js' {
  declare module.exports: $Exports<'react-apollo/flow-typed/npm/minimist_v1.x.x'>;
}
declare module 'react-apollo/flow-typed/npm/mobx-react_vx.x.x.js' {
  declare module.exports: $Exports<'react-apollo/flow-typed/npm/mobx-react_vx.x.x'>;
}
declare module 'react-apollo/flow-typed/npm/object-assign_v4.x.x.js' {
  declare module.exports: $Exports<'react-apollo/flow-typed/npm/object-assign_v4.x.x'>;
}
declare module 'react-apollo/flow-typed/npm/pre-commit_vx.x.x.js' {
  declare module.exports: $Exports<'react-apollo/flow-typed/npm/pre-commit_vx.x.x'>;
}
declare module 'react-apollo/flow-typed/npm/prettier_vx.x.x.js' {
  declare module.exports: $Exports<'react-apollo/flow-typed/npm/prettier_vx.x.x'>;
}
declare module 'react-apollo/flow-typed/npm/pretty-bytes_vx.x.x.js' {
  declare module.exports: $Exports<'react-apollo/flow-typed/npm/pretty-bytes_vx.x.x'>;
}
declare module 'react-apollo/flow-typed/npm/prop-types_v15.x.x.js' {
  declare module.exports: $Exports<'react-apollo/flow-typed/npm/prop-types_v15.x.x'>;
}
declare module 'react-apollo/flow-typed/npm/react-addons-test-utils_v15.x.x.js' {
  declare module.exports: $Exports<'react-apollo/flow-typed/npm/react-addons-test-utils_v15.x.x'>;
}
declare module 'react-apollo/flow-typed/npm/react-redux_v5.x.x.js' {
  declare module.exports: $Exports<'react-apollo/flow-typed/npm/react-redux_v5.x.x'>;
}
declare module 'react-apollo/flow-typed/npm/react-test-renderer_vx.x.x.js' {
  declare module.exports: $Exports<'react-apollo/flow-typed/npm/react-test-renderer_vx.x.x'>;
}
declare module 'react-apollo/flow-typed/npm/recompose_vx.x.x.js' {
  declare module.exports: $Exports<'react-apollo/flow-typed/npm/recompose_vx.x.x'>;
}
declare module 'react-apollo/flow-typed/npm/redux_vx.x.x.js' {
  declare module.exports: $Exports<'react-apollo/flow-typed/npm/redux_vx.x.x'>;
}
declare module 'react-apollo/flow-typed/npm/redux-form_vx.x.x.js' {
  declare module.exports: $Exports<'react-apollo/flow-typed/npm/redux-form_vx.x.x'>;
}
declare module 'react-apollo/flow-typed/npm/redux-immutable_vx.x.x.js' {
  declare module.exports: $Exports<'react-apollo/flow-typed/npm/redux-immutable_vx.x.x'>;
}
declare module 'react-apollo/flow-typed/npm/redux-loop_v2.2.x.js' {
  declare module.exports: $Exports<'react-apollo/flow-typed/npm/redux-loop_v2.2.x'>;
}
declare module 'react-apollo/flow-typed/npm/rollup_vx.x.x.js' {
  declare module.exports: $Exports<'react-apollo/flow-typed/npm/rollup_vx.x.x'>;
}
declare module 'react-apollo/flow-typed/npm/source-map-support_vx.x.x.js' {
  declare module.exports: $Exports<'react-apollo/flow-typed/npm/source-map-support_vx.x.x'>;
}
declare module 'react-apollo/flow-typed/npm/swapi-graphql_vx.x.x.js' {
  declare module.exports: $Exports<'react-apollo/flow-typed/npm/swapi-graphql_vx.x.x'>;
}
declare module 'react-apollo/flow-typed/npm/travis-weigh-in_vx.x.x.js' {
  declare module.exports: $Exports<'react-apollo/flow-typed/npm/travis-weigh-in_vx.x.x'>;
}
declare module 'react-apollo/flow-typed/npm/tslint_vx.x.x.js' {
  declare module.exports: $Exports<'react-apollo/flow-typed/npm/tslint_vx.x.x'>;
}
declare module 'react-apollo/flow-typed/npm/typescript_vx.x.x.js' {
  declare module.exports: $Exports<'react-apollo/flow-typed/npm/typescript_vx.x.x'>;
}
declare module 'react-apollo/flow-typed/npm/typescript-require_vx.x.x.js' {
  declare module.exports: $Exports<'react-apollo/flow-typed/npm/typescript-require_vx.x.x'>;
}
declare module 'react-apollo/flow-typed/npm/typings_vx.x.x.js' {
  declare module.exports: $Exports<'react-apollo/flow-typed/npm/typings_vx.x.x'>;
}
declare module 'react-apollo/flow-typed/npm/uglify-js_vx.x.x.js' {
  declare module.exports: $Exports<'react-apollo/flow-typed/npm/uglify-js_vx.x.x'>;
}
declare module 'react-apollo/graphql.js' {
  declare module.exports: $Exports<'react-apollo/graphql'>;
}
declare module 'react-apollo/index' {
  declare module.exports: $Exports<'react-apollo'>;
}
declare module 'react-apollo/index.js' {
  declare module.exports: $Exports<'react-apollo'>;
}
declare module 'react-apollo/parser.js' {
  declare module.exports: $Exports<'react-apollo/parser'>;
}
declare module 'react-apollo/queryRecycler.js' {
  declare module.exports: $Exports<'react-apollo/queryRecycler'>;
}
declare module 'react-apollo/react-apollo.browser.umd.js' {
  declare module.exports: $Exports<'react-apollo/react-apollo.browser.umd'>;
}
declare module 'react-apollo/react-apollo.umd.js' {
  declare module.exports: $Exports<'react-apollo/react-apollo.umd'>;
}
declare module 'react-apollo/server.js' {
  declare module.exports: $Exports<'react-apollo/server'>;
}
declare module 'react-apollo/shallowEqual.js' {
  declare module.exports: $Exports<'react-apollo/shallowEqual'>;
}
declare module 'react-apollo/test-utils.js' {
  declare module.exports: $Exports<'react-apollo/test-utils'>;
}
declare module 'react-apollo/types.js' {
  declare module.exports: $Exports<'react-apollo/types'>;
}
declare module 'react-apollo/withApollo.js' {
  declare module.exports: $Exports<'react-apollo/withApollo'>;
}
