// flow-typed signature: 0b1b73dfddf3d2c5cdc792811e4a6cf2
// flow-typed version: <<STUB>>/react-map-gl_v2.0.x/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-map-gl'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-map-gl' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-map-gl/dist/config' {
  declare module.exports: any;
}

declare module 'react-map-gl/dist/index' {
  declare module.exports: any;
}

declare module 'react-map-gl/dist/map-interactions.react' {
  declare module.exports: any;
}

declare module 'react-map-gl/dist/map.react' {
  declare module.exports: any;
}

declare module 'react-map-gl/dist/overlays/canvas.react' {
  declare module.exports: any;
}

declare module 'react-map-gl/dist/overlays/choropleth.react' {
  declare module.exports: any;
}

declare module 'react-map-gl/dist/overlays/draggable-points.react' {
  declare module.exports: any;
}

declare module 'react-map-gl/dist/overlays/html.react' {
  declare module.exports: any;
}

declare module 'react-map-gl/dist/overlays/index' {
  declare module.exports: any;
}

declare module 'react-map-gl/dist/overlays/scatterplot.react' {
  declare module.exports: any;
}

declare module 'react-map-gl/dist/overlays/svg.react' {
  declare module.exports: any;
}

declare module 'react-map-gl/dist/utils/alphaify' {
  declare module.exports: any;
}

declare module 'react-map-gl/dist/utils/diff-styles' {
  declare module.exports: any;
}

declare module 'react-map-gl/dist/utils/fit-bounds' {
  declare module.exports: any;
}

declare module 'react-map-gl/dist/utils/style-utils' {
  declare module.exports: any;
}

declare module 'react-map-gl/dist/utils/transform' {
  declare module.exports: any;
}

declare module 'react-map-gl/postinstall' {
  declare module.exports: any;
}

declare module 'react-map-gl/src/config' {
  declare module.exports: any;
}

declare module 'react-map-gl/src/index' {
  declare module.exports: any;
}

declare module 'react-map-gl/src/map-interactions.react' {
  declare module.exports: any;
}

declare module 'react-map-gl/src/map.react' {
  declare module.exports: any;
}

declare module 'react-map-gl/src/overlays/canvas.react' {
  declare module.exports: any;
}

declare module 'react-map-gl/src/overlays/choropleth.react' {
  declare module.exports: any;
}

declare module 'react-map-gl/src/overlays/draggable-points.react' {
  declare module.exports: any;
}

declare module 'react-map-gl/src/overlays/html.react' {
  declare module.exports: any;
}

declare module 'react-map-gl/src/overlays/index' {
  declare module.exports: any;
}

declare module 'react-map-gl/src/overlays/scatterplot.react' {
  declare module.exports: any;
}

declare module 'react-map-gl/src/overlays/svg.react' {
  declare module.exports: any;
}

declare module 'react-map-gl/src/utils/alphaify' {
  declare module.exports: any;
}

declare module 'react-map-gl/src/utils/diff-styles' {
  declare module.exports: any;
}

declare module 'react-map-gl/src/utils/fit-bounds' {
  declare module.exports: any;
}

declare module 'react-map-gl/src/utils/style-utils' {
  declare module.exports: any;
}

declare module 'react-map-gl/src/utils/transform' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-map-gl/dist/config.js' {
  declare module.exports: $Exports<'react-map-gl/dist/config'>;
}
declare module 'react-map-gl/dist/index.js' {
  declare module.exports: $Exports<'react-map-gl/dist/index'>;
}
declare module 'react-map-gl/dist/map-interactions.react.js' {
  declare module.exports: $Exports<'react-map-gl/dist/map-interactions.react'>;
}
declare module 'react-map-gl/dist/map.react.js' {
  declare module.exports: $Exports<'react-map-gl/dist/map.react'>;
}
declare module 'react-map-gl/dist/overlays/canvas.react.js' {
  declare module.exports: $Exports<'react-map-gl/dist/overlays/canvas.react'>;
}
declare module 'react-map-gl/dist/overlays/choropleth.react.js' {
  declare module.exports: $Exports<'react-map-gl/dist/overlays/choropleth.react'>;
}
declare module 'react-map-gl/dist/overlays/draggable-points.react.js' {
  declare module.exports: $Exports<'react-map-gl/dist/overlays/draggable-points.react'>;
}
declare module 'react-map-gl/dist/overlays/html.react.js' {
  declare module.exports: $Exports<'react-map-gl/dist/overlays/html.react'>;
}
declare module 'react-map-gl/dist/overlays/index.js' {
  declare module.exports: $Exports<'react-map-gl/dist/overlays/index'>;
}
declare module 'react-map-gl/dist/overlays/scatterplot.react.js' {
  declare module.exports: $Exports<'react-map-gl/dist/overlays/scatterplot.react'>;
}
declare module 'react-map-gl/dist/overlays/svg.react.js' {
  declare module.exports: $Exports<'react-map-gl/dist/overlays/svg.react'>;
}
declare module 'react-map-gl/dist/utils/alphaify.js' {
  declare module.exports: $Exports<'react-map-gl/dist/utils/alphaify'>;
}
declare module 'react-map-gl/dist/utils/diff-styles.js' {
  declare module.exports: $Exports<'react-map-gl/dist/utils/diff-styles'>;
}
declare module 'react-map-gl/dist/utils/fit-bounds.js' {
  declare module.exports: $Exports<'react-map-gl/dist/utils/fit-bounds'>;
}
declare module 'react-map-gl/dist/utils/style-utils.js' {
  declare module.exports: $Exports<'react-map-gl/dist/utils/style-utils'>;
}
declare module 'react-map-gl/dist/utils/transform.js' {
  declare module.exports: $Exports<'react-map-gl/dist/utils/transform'>;
}
declare module 'react-map-gl/index' {
  declare module.exports: $Exports<'react-map-gl'>;
}
declare module 'react-map-gl/index.js' {
  declare module.exports: $Exports<'react-map-gl'>;
}
declare module 'react-map-gl/postinstall.js' {
  declare module.exports: $Exports<'react-map-gl/postinstall'>;
}
declare module 'react-map-gl/src/config.js' {
  declare module.exports: $Exports<'react-map-gl/src/config'>;
}
declare module 'react-map-gl/src/index.js' {
  declare module.exports: $Exports<'react-map-gl/src/index'>;
}
declare module 'react-map-gl/src/map-interactions.react.js' {
  declare module.exports: $Exports<'react-map-gl/src/map-interactions.react'>;
}
declare module 'react-map-gl/src/map.react.js' {
  declare module.exports: $Exports<'react-map-gl/src/map.react'>;
}
declare module 'react-map-gl/src/overlays/canvas.react.js' {
  declare module.exports: $Exports<'react-map-gl/src/overlays/canvas.react'>;
}
declare module 'react-map-gl/src/overlays/choropleth.react.js' {
  declare module.exports: $Exports<'react-map-gl/src/overlays/choropleth.react'>;
}
declare module 'react-map-gl/src/overlays/draggable-points.react.js' {
  declare module.exports: $Exports<'react-map-gl/src/overlays/draggable-points.react'>;
}
declare module 'react-map-gl/src/overlays/html.react.js' {
  declare module.exports: $Exports<'react-map-gl/src/overlays/html.react'>;
}
declare module 'react-map-gl/src/overlays/index.js' {
  declare module.exports: $Exports<'react-map-gl/src/overlays/index'>;
}
declare module 'react-map-gl/src/overlays/scatterplot.react.js' {
  declare module.exports: $Exports<'react-map-gl/src/overlays/scatterplot.react'>;
}
declare module 'react-map-gl/src/overlays/svg.react.js' {
  declare module.exports: $Exports<'react-map-gl/src/overlays/svg.react'>;
}
declare module 'react-map-gl/src/utils/alphaify.js' {
  declare module.exports: $Exports<'react-map-gl/src/utils/alphaify'>;
}
declare module 'react-map-gl/src/utils/diff-styles.js' {
  declare module.exports: $Exports<'react-map-gl/src/utils/diff-styles'>;
}
declare module 'react-map-gl/src/utils/fit-bounds.js' {
  declare module.exports: $Exports<'react-map-gl/src/utils/fit-bounds'>;
}
declare module 'react-map-gl/src/utils/style-utils.js' {
  declare module.exports: $Exports<'react-map-gl/src/utils/style-utils'>;
}
declare module 'react-map-gl/src/utils/transform.js' {
  declare module.exports: $Exports<'react-map-gl/src/utils/transform'>;
}
