// flow-typed signature: 87bd335195b1e48e5cffd56685884ef8
// flow-typed version: <<STUB>>/react-intersection-observer_v1.0.0/flow_v0.52.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-intersection-observer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-intersection-observer' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-intersection-observer/es/index' {
  declare module.exports: any;
}

declare module 'react-intersection-observer/es/intersection' {
  declare module.exports: any;
}

declare module 'react-intersection-observer/lib/index' {
  declare module.exports: any;
}

declare module 'react-intersection-observer/lib/intersection' {
  declare module.exports: any;
}

declare module 'react-intersection-observer/src/index' {
  declare module.exports: any;
}

declare module 'react-intersection-observer/src/intersection' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-intersection-observer/es/index.js' {
  declare module.exports: $Exports<'react-intersection-observer/es/index'>;
}
declare module 'react-intersection-observer/es/intersection.js' {
  declare module.exports: $Exports<'react-intersection-observer/es/intersection'>;
}
declare module 'react-intersection-observer/lib/index.js' {
  declare module.exports: $Exports<'react-intersection-observer/lib/index'>;
}
declare module 'react-intersection-observer/lib/intersection.js' {
  declare module.exports: $Exports<'react-intersection-observer/lib/intersection'>;
}
declare module 'react-intersection-observer/src/index.js' {
  declare module.exports: $Exports<'react-intersection-observer/src/index'>;
}
declare module 'react-intersection-observer/src/intersection.js' {
  declare module.exports: $Exports<'react-intersection-observer/src/intersection'>;
}
