// flow-typed signature: e698a32b5882d3e806035180d4026bef
// flow-typed version: <<STUB>>/react-beautiful-dnd_v2.5.0/flow_v0.52.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-beautiful-dnd'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-beautiful-dnd' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-beautiful-dnd/flow-typed/npm/@atlaskit/css-reset_vx.x.x' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/flow-typed/npm/@storybook/react_vx.x.x' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/flow-typed/npm/enzyme_v2.3.x' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/flow-typed/npm/invariant_v2.x.x' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/flow-typed/npm/jest_v20.x.x' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/flow-typed/npm/prop-types_v15.x.x' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/flow-typed/npm/react-redux_v5.x.x' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/flow-typed/npm/redux_v3.x.x' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/flow-typed/npm/reselect_v3.x.x' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/flow-typed/npm/styled-components_v2.x.x' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/lib/index' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/lib/state/action-creators' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/lib/state/axis' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/lib/state/create-store' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/lib/state/dimension' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/lib/state/fire-hooks' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/lib/state/get-client-rect' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/lib/state/get-drag-impact/in-foreign-list' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/lib/state/get-drag-impact/in-home-list' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/lib/state/get-drag-impact/index' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/lib/state/get-draggables-inside-droppable' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/lib/state/get-droppable-over' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/lib/state/get-initial-impact' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/lib/state/get-new-home-client-center' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/lib/state/is-within-visible-bounds-of-droppable' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/lib/state/is-within' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/lib/state/log-middleware' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/lib/state/move-cross-axis/get-best-cross-axis-droppable' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/lib/state/move-cross-axis/get-closest-draggable' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/lib/state/move-cross-axis/index' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/lib/state/move-cross-axis/move-cross-axis-types' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/lib/state/move-cross-axis/move-to-new-droppable/index' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/lib/state/move-cross-axis/move-to-new-droppable/to-foreign-list' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/lib/state/move-cross-axis/move-to-new-droppable/to-home-list' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/lib/state/move-to-edge' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/lib/state/move-to-next-index/in-foreign-list' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/lib/state/move-to-next-index/in-home-list' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/lib/state/move-to-next-index/index' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/lib/state/move-to-next-index/move-to-next-index-types' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/lib/state/no-impact' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/lib/state/position' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/lib/state/reducer' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/lib/state/selectors' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/lib/state/spacing' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/lib/types' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/lib/view/animation' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/lib/view/context-keys' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/lib/view/drag-drop-context/drag-drop-context' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/lib/view/drag-drop-context/index' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/lib/view/drag-handle/drag-handle-types' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/lib/view/drag-handle/drag-handle' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/lib/view/drag-handle/index' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/lib/view/draggable-dimension-publisher/connected-draggable-dimension-publisher' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/lib/view/draggable-dimension-publisher/draggable-dimension-publisher-types' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/lib/view/draggable-dimension-publisher/draggable-dimension-publisher' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/lib/view/draggable-dimension-publisher/index' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/lib/view/draggable/connected-draggable' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/lib/view/draggable/draggable-types' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/lib/view/draggable/draggable' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/lib/view/draggable/index' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/lib/view/droppable-dimension-publisher/connected-droppable-dimension-publisher' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/lib/view/droppable-dimension-publisher/droppable-dimension-publisher-types' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/lib/view/droppable-dimension-publisher/droppable-dimension-publisher' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/lib/view/droppable-dimension-publisher/index' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/lib/view/droppable/connected-droppable' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/lib/view/droppable/droppable-types' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/lib/view/droppable/droppable' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/lib/view/droppable/index' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/lib/view/get-center-position' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/lib/view/get-closest-scrollable' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/lib/view/get-window-scroll-position' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/lib/view/key-codes' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/lib/view/moveable/index' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/lib/view/moveable/moveable-types' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/lib/view/moveable/moveable' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/lib/view/placeholder/index' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/lib/view/placeholder/placeholder' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/index' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/action-creators' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/axis' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/create-store' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/dimension' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/fire-hooks' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/get-client-rect' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/get-drag-impact/in-foreign-list' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/get-drag-impact/in-home-list' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/get-drag-impact/index' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/get-draggables-inside-droppable' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/get-droppable-over' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/get-initial-impact' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/get-new-home-client-center' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/is-within-visible-bounds-of-droppable' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/is-within' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/log-middleware' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/move-cross-axis/get-best-cross-axis-droppable' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/move-cross-axis/get-closest-draggable' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/move-cross-axis/index' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/move-cross-axis/move-cross-axis-types' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/move-cross-axis/move-to-new-droppable/index' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/move-cross-axis/move-to-new-droppable/to-foreign-list' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/move-cross-axis/move-to-new-droppable/to-home-list' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/move-to-edge' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/move-to-next-index/in-foreign-list' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/move-to-next-index/in-home-list' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/move-to-next-index/index' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/move-to-next-index/move-to-next-index-types' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/no-impact' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/position' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/reducer' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/selectors' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/state/spacing' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/types' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/view/animation' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/view/context-keys' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/view/drag-drop-context/drag-drop-context' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/view/drag-drop-context/index' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/view/drag-handle/drag-handle-types' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/view/drag-handle/drag-handle' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/view/drag-handle/index' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/view/draggable-dimension-publisher/connected-draggable-dimension-publisher' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/view/draggable-dimension-publisher/draggable-dimension-publisher-types' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/view/draggable-dimension-publisher/draggable-dimension-publisher' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/view/draggable-dimension-publisher/index' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/view/draggable/connected-draggable' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/view/draggable/draggable-types' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/view/draggable/draggable' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/view/draggable/index' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/view/droppable-dimension-publisher/connected-droppable-dimension-publisher' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/view/droppable-dimension-publisher/droppable-dimension-publisher-types' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/view/droppable-dimension-publisher/droppable-dimension-publisher' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/view/droppable-dimension-publisher/index' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/view/droppable/connected-droppable' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/view/droppable/droppable-types' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/view/droppable/droppable' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/view/droppable/index' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/view/get-center-position' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/view/get-closest-scrollable' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/view/get-window-scroll-position' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/view/key-codes' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/view/moveable/index' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/view/moveable/moveable-types' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/view/moveable/moveable' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/view/placeholder/index' {
  declare module.exports: any;
}

declare module 'react-beautiful-dnd/src/view/placeholder/placeholder' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-beautiful-dnd/flow-typed/npm/@atlaskit/css-reset_vx.x.x.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/flow-typed/npm/@atlaskit/css-reset_vx.x.x'>;
}
declare module 'react-beautiful-dnd/flow-typed/npm/@storybook/react_vx.x.x.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/flow-typed/npm/@storybook/react_vx.x.x'>;
}
declare module 'react-beautiful-dnd/flow-typed/npm/enzyme_v2.3.x.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/flow-typed/npm/enzyme_v2.3.x'>;
}
declare module 'react-beautiful-dnd/flow-typed/npm/invariant_v2.x.x.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/flow-typed/npm/invariant_v2.x.x'>;
}
declare module 'react-beautiful-dnd/flow-typed/npm/jest_v20.x.x.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/flow-typed/npm/jest_v20.x.x'>;
}
declare module 'react-beautiful-dnd/flow-typed/npm/prop-types_v15.x.x.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/flow-typed/npm/prop-types_v15.x.x'>;
}
declare module 'react-beautiful-dnd/flow-typed/npm/react-redux_v5.x.x.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/flow-typed/npm/react-redux_v5.x.x'>;
}
declare module 'react-beautiful-dnd/flow-typed/npm/redux_v3.x.x.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/flow-typed/npm/redux_v3.x.x'>;
}
declare module 'react-beautiful-dnd/flow-typed/npm/reselect_v3.x.x.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/flow-typed/npm/reselect_v3.x.x'>;
}
declare module 'react-beautiful-dnd/flow-typed/npm/styled-components_v2.x.x.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/flow-typed/npm/styled-components_v2.x.x'>;
}
declare module 'react-beautiful-dnd/lib/index.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/lib/index'>;
}
declare module 'react-beautiful-dnd/lib/state/action-creators.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/lib/state/action-creators'>;
}
declare module 'react-beautiful-dnd/lib/state/axis.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/lib/state/axis'>;
}
declare module 'react-beautiful-dnd/lib/state/create-store.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/lib/state/create-store'>;
}
declare module 'react-beautiful-dnd/lib/state/dimension.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/lib/state/dimension'>;
}
declare module 'react-beautiful-dnd/lib/state/fire-hooks.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/lib/state/fire-hooks'>;
}
declare module 'react-beautiful-dnd/lib/state/get-client-rect.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/lib/state/get-client-rect'>;
}
declare module 'react-beautiful-dnd/lib/state/get-drag-impact/in-foreign-list.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/lib/state/get-drag-impact/in-foreign-list'>;
}
declare module 'react-beautiful-dnd/lib/state/get-drag-impact/in-home-list.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/lib/state/get-drag-impact/in-home-list'>;
}
declare module 'react-beautiful-dnd/lib/state/get-drag-impact/index.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/lib/state/get-drag-impact/index'>;
}
declare module 'react-beautiful-dnd/lib/state/get-draggables-inside-droppable.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/lib/state/get-draggables-inside-droppable'>;
}
declare module 'react-beautiful-dnd/lib/state/get-droppable-over.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/lib/state/get-droppable-over'>;
}
declare module 'react-beautiful-dnd/lib/state/get-initial-impact.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/lib/state/get-initial-impact'>;
}
declare module 'react-beautiful-dnd/lib/state/get-new-home-client-center.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/lib/state/get-new-home-client-center'>;
}
declare module 'react-beautiful-dnd/lib/state/is-within-visible-bounds-of-droppable.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/lib/state/is-within-visible-bounds-of-droppable'>;
}
declare module 'react-beautiful-dnd/lib/state/is-within.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/lib/state/is-within'>;
}
declare module 'react-beautiful-dnd/lib/state/log-middleware.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/lib/state/log-middleware'>;
}
declare module 'react-beautiful-dnd/lib/state/move-cross-axis/get-best-cross-axis-droppable.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/lib/state/move-cross-axis/get-best-cross-axis-droppable'>;
}
declare module 'react-beautiful-dnd/lib/state/move-cross-axis/get-closest-draggable.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/lib/state/move-cross-axis/get-closest-draggable'>;
}
declare module 'react-beautiful-dnd/lib/state/move-cross-axis/index.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/lib/state/move-cross-axis/index'>;
}
declare module 'react-beautiful-dnd/lib/state/move-cross-axis/move-cross-axis-types.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/lib/state/move-cross-axis/move-cross-axis-types'>;
}
declare module 'react-beautiful-dnd/lib/state/move-cross-axis/move-to-new-droppable/index.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/lib/state/move-cross-axis/move-to-new-droppable/index'>;
}
declare module 'react-beautiful-dnd/lib/state/move-cross-axis/move-to-new-droppable/to-foreign-list.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/lib/state/move-cross-axis/move-to-new-droppable/to-foreign-list'>;
}
declare module 'react-beautiful-dnd/lib/state/move-cross-axis/move-to-new-droppable/to-home-list.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/lib/state/move-cross-axis/move-to-new-droppable/to-home-list'>;
}
declare module 'react-beautiful-dnd/lib/state/move-to-edge.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/lib/state/move-to-edge'>;
}
declare module 'react-beautiful-dnd/lib/state/move-to-next-index/in-foreign-list.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/lib/state/move-to-next-index/in-foreign-list'>;
}
declare module 'react-beautiful-dnd/lib/state/move-to-next-index/in-home-list.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/lib/state/move-to-next-index/in-home-list'>;
}
declare module 'react-beautiful-dnd/lib/state/move-to-next-index/index.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/lib/state/move-to-next-index/index'>;
}
declare module 'react-beautiful-dnd/lib/state/move-to-next-index/move-to-next-index-types.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/lib/state/move-to-next-index/move-to-next-index-types'>;
}
declare module 'react-beautiful-dnd/lib/state/no-impact.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/lib/state/no-impact'>;
}
declare module 'react-beautiful-dnd/lib/state/position.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/lib/state/position'>;
}
declare module 'react-beautiful-dnd/lib/state/reducer.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/lib/state/reducer'>;
}
declare module 'react-beautiful-dnd/lib/state/selectors.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/lib/state/selectors'>;
}
declare module 'react-beautiful-dnd/lib/state/spacing.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/lib/state/spacing'>;
}
declare module 'react-beautiful-dnd/lib/types.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/lib/types'>;
}
declare module 'react-beautiful-dnd/lib/view/animation.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/lib/view/animation'>;
}
declare module 'react-beautiful-dnd/lib/view/context-keys.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/lib/view/context-keys'>;
}
declare module 'react-beautiful-dnd/lib/view/drag-drop-context/drag-drop-context.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/lib/view/drag-drop-context/drag-drop-context'>;
}
declare module 'react-beautiful-dnd/lib/view/drag-drop-context/index.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/lib/view/drag-drop-context/index'>;
}
declare module 'react-beautiful-dnd/lib/view/drag-handle/drag-handle-types.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/lib/view/drag-handle/drag-handle-types'>;
}
declare module 'react-beautiful-dnd/lib/view/drag-handle/drag-handle.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/lib/view/drag-handle/drag-handle'>;
}
declare module 'react-beautiful-dnd/lib/view/drag-handle/index.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/lib/view/drag-handle/index'>;
}
declare module 'react-beautiful-dnd/lib/view/draggable-dimension-publisher/connected-draggable-dimension-publisher.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/lib/view/draggable-dimension-publisher/connected-draggable-dimension-publisher'>;
}
declare module 'react-beautiful-dnd/lib/view/draggable-dimension-publisher/draggable-dimension-publisher-types.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/lib/view/draggable-dimension-publisher/draggable-dimension-publisher-types'>;
}
declare module 'react-beautiful-dnd/lib/view/draggable-dimension-publisher/draggable-dimension-publisher.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/lib/view/draggable-dimension-publisher/draggable-dimension-publisher'>;
}
declare module 'react-beautiful-dnd/lib/view/draggable-dimension-publisher/index.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/lib/view/draggable-dimension-publisher/index'>;
}
declare module 'react-beautiful-dnd/lib/view/draggable/connected-draggable.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/lib/view/draggable/connected-draggable'>;
}
declare module 'react-beautiful-dnd/lib/view/draggable/draggable-types.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/lib/view/draggable/draggable-types'>;
}
declare module 'react-beautiful-dnd/lib/view/draggable/draggable.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/lib/view/draggable/draggable'>;
}
declare module 'react-beautiful-dnd/lib/view/draggable/index.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/lib/view/draggable/index'>;
}
declare module 'react-beautiful-dnd/lib/view/droppable-dimension-publisher/connected-droppable-dimension-publisher.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/lib/view/droppable-dimension-publisher/connected-droppable-dimension-publisher'>;
}
declare module 'react-beautiful-dnd/lib/view/droppable-dimension-publisher/droppable-dimension-publisher-types.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/lib/view/droppable-dimension-publisher/droppable-dimension-publisher-types'>;
}
declare module 'react-beautiful-dnd/lib/view/droppable-dimension-publisher/droppable-dimension-publisher.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/lib/view/droppable-dimension-publisher/droppable-dimension-publisher'>;
}
declare module 'react-beautiful-dnd/lib/view/droppable-dimension-publisher/index.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/lib/view/droppable-dimension-publisher/index'>;
}
declare module 'react-beautiful-dnd/lib/view/droppable/connected-droppable.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/lib/view/droppable/connected-droppable'>;
}
declare module 'react-beautiful-dnd/lib/view/droppable/droppable-types.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/lib/view/droppable/droppable-types'>;
}
declare module 'react-beautiful-dnd/lib/view/droppable/droppable.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/lib/view/droppable/droppable'>;
}
declare module 'react-beautiful-dnd/lib/view/droppable/index.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/lib/view/droppable/index'>;
}
declare module 'react-beautiful-dnd/lib/view/get-center-position.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/lib/view/get-center-position'>;
}
declare module 'react-beautiful-dnd/lib/view/get-closest-scrollable.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/lib/view/get-closest-scrollable'>;
}
declare module 'react-beautiful-dnd/lib/view/get-window-scroll-position.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/lib/view/get-window-scroll-position'>;
}
declare module 'react-beautiful-dnd/lib/view/key-codes.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/lib/view/key-codes'>;
}
declare module 'react-beautiful-dnd/lib/view/moveable/index.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/lib/view/moveable/index'>;
}
declare module 'react-beautiful-dnd/lib/view/moveable/moveable-types.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/lib/view/moveable/moveable-types'>;
}
declare module 'react-beautiful-dnd/lib/view/moveable/moveable.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/lib/view/moveable/moveable'>;
}
declare module 'react-beautiful-dnd/lib/view/placeholder/index.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/lib/view/placeholder/index'>;
}
declare module 'react-beautiful-dnd/lib/view/placeholder/placeholder.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/lib/view/placeholder/placeholder'>;
}
declare module 'react-beautiful-dnd/src/index.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/index'>;
}
declare module 'react-beautiful-dnd/src/state/action-creators.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/action-creators'>;
}
declare module 'react-beautiful-dnd/src/state/axis.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/axis'>;
}
declare module 'react-beautiful-dnd/src/state/create-store.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/create-store'>;
}
declare module 'react-beautiful-dnd/src/state/dimension.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/dimension'>;
}
declare module 'react-beautiful-dnd/src/state/fire-hooks.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/fire-hooks'>;
}
declare module 'react-beautiful-dnd/src/state/get-client-rect.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/get-client-rect'>;
}
declare module 'react-beautiful-dnd/src/state/get-drag-impact/in-foreign-list.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/get-drag-impact/in-foreign-list'>;
}
declare module 'react-beautiful-dnd/src/state/get-drag-impact/in-home-list.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/get-drag-impact/in-home-list'>;
}
declare module 'react-beautiful-dnd/src/state/get-drag-impact/index.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/get-drag-impact/index'>;
}
declare module 'react-beautiful-dnd/src/state/get-draggables-inside-droppable.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/get-draggables-inside-droppable'>;
}
declare module 'react-beautiful-dnd/src/state/get-droppable-over.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/get-droppable-over'>;
}
declare module 'react-beautiful-dnd/src/state/get-initial-impact.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/get-initial-impact'>;
}
declare module 'react-beautiful-dnd/src/state/get-new-home-client-center.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/get-new-home-client-center'>;
}
declare module 'react-beautiful-dnd/src/state/is-within-visible-bounds-of-droppable.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/is-within-visible-bounds-of-droppable'>;
}
declare module 'react-beautiful-dnd/src/state/is-within.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/is-within'>;
}
declare module 'react-beautiful-dnd/src/state/log-middleware.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/log-middleware'>;
}
declare module 'react-beautiful-dnd/src/state/move-cross-axis/get-best-cross-axis-droppable.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/move-cross-axis/get-best-cross-axis-droppable'>;
}
declare module 'react-beautiful-dnd/src/state/move-cross-axis/get-closest-draggable.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/move-cross-axis/get-closest-draggable'>;
}
declare module 'react-beautiful-dnd/src/state/move-cross-axis/index.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/move-cross-axis/index'>;
}
declare module 'react-beautiful-dnd/src/state/move-cross-axis/move-cross-axis-types.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/move-cross-axis/move-cross-axis-types'>;
}
declare module 'react-beautiful-dnd/src/state/move-cross-axis/move-to-new-droppable/index.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/move-cross-axis/move-to-new-droppable/index'>;
}
declare module 'react-beautiful-dnd/src/state/move-cross-axis/move-to-new-droppable/to-foreign-list.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/move-cross-axis/move-to-new-droppable/to-foreign-list'>;
}
declare module 'react-beautiful-dnd/src/state/move-cross-axis/move-to-new-droppable/to-home-list.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/move-cross-axis/move-to-new-droppable/to-home-list'>;
}
declare module 'react-beautiful-dnd/src/state/move-to-edge.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/move-to-edge'>;
}
declare module 'react-beautiful-dnd/src/state/move-to-next-index/in-foreign-list.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/move-to-next-index/in-foreign-list'>;
}
declare module 'react-beautiful-dnd/src/state/move-to-next-index/in-home-list.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/move-to-next-index/in-home-list'>;
}
declare module 'react-beautiful-dnd/src/state/move-to-next-index/index.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/move-to-next-index/index'>;
}
declare module 'react-beautiful-dnd/src/state/move-to-next-index/move-to-next-index-types.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/move-to-next-index/move-to-next-index-types'>;
}
declare module 'react-beautiful-dnd/src/state/no-impact.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/no-impact'>;
}
declare module 'react-beautiful-dnd/src/state/position.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/position'>;
}
declare module 'react-beautiful-dnd/src/state/reducer.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/reducer'>;
}
declare module 'react-beautiful-dnd/src/state/selectors.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/selectors'>;
}
declare module 'react-beautiful-dnd/src/state/spacing.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/state/spacing'>;
}
declare module 'react-beautiful-dnd/src/types.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/types'>;
}
declare module 'react-beautiful-dnd/src/view/animation.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/view/animation'>;
}
declare module 'react-beautiful-dnd/src/view/context-keys.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/view/context-keys'>;
}
declare module 'react-beautiful-dnd/src/view/drag-drop-context/drag-drop-context.jsx' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/view/drag-drop-context/drag-drop-context'>;
}
declare module 'react-beautiful-dnd/src/view/drag-drop-context/index.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/view/drag-drop-context/index'>;
}
declare module 'react-beautiful-dnd/src/view/drag-handle/drag-handle-types.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/view/drag-handle/drag-handle-types'>;
}
declare module 'react-beautiful-dnd/src/view/drag-handle/drag-handle.jsx' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/view/drag-handle/drag-handle'>;
}
declare module 'react-beautiful-dnd/src/view/drag-handle/index.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/view/drag-handle/index'>;
}
declare module 'react-beautiful-dnd/src/view/draggable-dimension-publisher/connected-draggable-dimension-publisher.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/view/draggable-dimension-publisher/connected-draggable-dimension-publisher'>;
}
declare module 'react-beautiful-dnd/src/view/draggable-dimension-publisher/draggable-dimension-publisher-types.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/view/draggable-dimension-publisher/draggable-dimension-publisher-types'>;
}
declare module 'react-beautiful-dnd/src/view/draggable-dimension-publisher/draggable-dimension-publisher.jsx' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/view/draggable-dimension-publisher/draggable-dimension-publisher'>;
}
declare module 'react-beautiful-dnd/src/view/draggable-dimension-publisher/index.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/view/draggable-dimension-publisher/index'>;
}
declare module 'react-beautiful-dnd/src/view/draggable/connected-draggable.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/view/draggable/connected-draggable'>;
}
declare module 'react-beautiful-dnd/src/view/draggable/draggable-types.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/view/draggable/draggable-types'>;
}
declare module 'react-beautiful-dnd/src/view/draggable/draggable.jsx' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/view/draggable/draggable'>;
}
declare module 'react-beautiful-dnd/src/view/draggable/index.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/view/draggable/index'>;
}
declare module 'react-beautiful-dnd/src/view/droppable-dimension-publisher/connected-droppable-dimension-publisher.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/view/droppable-dimension-publisher/connected-droppable-dimension-publisher'>;
}
declare module 'react-beautiful-dnd/src/view/droppable-dimension-publisher/droppable-dimension-publisher-types.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/view/droppable-dimension-publisher/droppable-dimension-publisher-types'>;
}
declare module 'react-beautiful-dnd/src/view/droppable-dimension-publisher/droppable-dimension-publisher.jsx' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/view/droppable-dimension-publisher/droppable-dimension-publisher'>;
}
declare module 'react-beautiful-dnd/src/view/droppable-dimension-publisher/index.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/view/droppable-dimension-publisher/index'>;
}
declare module 'react-beautiful-dnd/src/view/droppable/connected-droppable.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/view/droppable/connected-droppable'>;
}
declare module 'react-beautiful-dnd/src/view/droppable/droppable-types.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/view/droppable/droppable-types'>;
}
declare module 'react-beautiful-dnd/src/view/droppable/droppable.jsx' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/view/droppable/droppable'>;
}
declare module 'react-beautiful-dnd/src/view/droppable/index.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/view/droppable/index'>;
}
declare module 'react-beautiful-dnd/src/view/get-center-position.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/view/get-center-position'>;
}
declare module 'react-beautiful-dnd/src/view/get-closest-scrollable.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/view/get-closest-scrollable'>;
}
declare module 'react-beautiful-dnd/src/view/get-window-scroll-position.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/view/get-window-scroll-position'>;
}
declare module 'react-beautiful-dnd/src/view/key-codes.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/view/key-codes'>;
}
declare module 'react-beautiful-dnd/src/view/moveable/index.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/view/moveable/index'>;
}
declare module 'react-beautiful-dnd/src/view/moveable/moveable-types.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/view/moveable/moveable-types'>;
}
declare module 'react-beautiful-dnd/src/view/moveable/moveable.jsx' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/view/moveable/moveable'>;
}
declare module 'react-beautiful-dnd/src/view/placeholder/index.js' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/view/placeholder/index'>;
}
declare module 'react-beautiful-dnd/src/view/placeholder/placeholder.jsx' {
  declare module.exports: $Exports<'react-beautiful-dnd/src/view/placeholder/placeholder'>;
}
