// flow-typed signature: 8d083a96a8e1a048de65ba17f72d7ca0
// flow-typed version: <<STUB>>/usus_v1.6.0/flow_v0.52.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'usus'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'usus' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'usus/chrome-linux/resources/inspector/accessibility/accessibility_module' {
  declare module.exports: any;
}

declare module 'usus/chrome-linux/resources/inspector/animation/animation_module' {
  declare module.exports: any;
}

declare module 'usus/chrome-linux/resources/inspector/audits/audits_module' {
  declare module.exports: any;
}

declare module 'usus/chrome-linux/resources/inspector/audits2_worker' {
  declare module.exports: any;
}

declare module 'usus/chrome-linux/resources/inspector/audits2_worker/audits2_worker_module' {
  declare module.exports: any;
}

declare module 'usus/chrome-linux/resources/inspector/audits2/audits2_module' {
  declare module.exports: any;
}

declare module 'usus/chrome-linux/resources/inspector/changes/changes_module' {
  declare module.exports: any;
}

declare module 'usus/chrome-linux/resources/inspector/cm_modes/cm_modes_module' {
  declare module.exports: any;
}

declare module 'usus/chrome-linux/resources/inspector/cm/cm_module' {
  declare module.exports: any;
}

declare module 'usus/chrome-linux/resources/inspector/color_picker/color_picker_module' {
  declare module.exports: any;
}

declare module 'usus/chrome-linux/resources/inspector/console_test_runner/console_test_runner_module' {
  declare module.exports: any;
}

declare module 'usus/chrome-linux/resources/inspector/console/console_module' {
  declare module.exports: any;
}

declare module 'usus/chrome-linux/resources/inspector/cookie_table/cookie_table_module' {
  declare module.exports: any;
}

declare module 'usus/chrome-linux/resources/inspector/data_grid/data_grid_module' {
  declare module.exports: any;
}

declare module 'usus/chrome-linux/resources/inspector/devices/devices_module' {
  declare module.exports: any;
}

declare module 'usus/chrome-linux/resources/inspector/devtools_compatibility' {
  declare module.exports: any;
}

declare module 'usus/chrome-linux/resources/inspector/devtools_extension_api' {
  declare module.exports: any;
}

declare module 'usus/chrome-linux/resources/inspector/diff/diff_module' {
  declare module.exports: any;
}

declare module 'usus/chrome-linux/resources/inspector/elements_test_runner/elements_test_runner_module' {
  declare module.exports: any;
}

declare module 'usus/chrome-linux/resources/inspector/elements/elements_module' {
  declare module.exports: any;
}

declare module 'usus/chrome-linux/resources/inspector/emulated_devices/emulated_devices_module' {
  declare module.exports: any;
}

declare module 'usus/chrome-linux/resources/inspector/event_listeners/event_listeners_module' {
  declare module.exports: any;
}

declare module 'usus/chrome-linux/resources/inspector/formatter_worker' {
  declare module.exports: any;
}

declare module 'usus/chrome-linux/resources/inspector/formatter/formatter_module' {
  declare module.exports: any;
}

declare module 'usus/chrome-linux/resources/inspector/gonzales/gonzales_module' {
  declare module.exports: any;
}

declare module 'usus/chrome-linux/resources/inspector/heap_snapshot_model/heap_snapshot_model_module' {
  declare module.exports: any;
}

declare module 'usus/chrome-linux/resources/inspector/heap_snapshot_worker' {
  declare module.exports: any;
}

declare module 'usus/chrome-linux/resources/inspector/inline_editor/inline_editor_module' {
  declare module.exports: any;
}

declare module 'usus/chrome-linux/resources/inspector/inspector' {
  declare module.exports: any;
}

declare module 'usus/chrome-linux/resources/inspector/InspectorBackendCommands' {
  declare module.exports: any;
}

declare module 'usus/chrome-linux/resources/inspector/integration_test_runner' {
  declare module.exports: any;
}

declare module 'usus/chrome-linux/resources/inspector/layer_viewer/layer_viewer_module' {
  declare module.exports: any;
}

declare module 'usus/chrome-linux/resources/inspector/layers/layers_module' {
  declare module.exports: any;
}

declare module 'usus/chrome-linux/resources/inspector/network_priorities/network_priorities_module' {
  declare module.exports: any;
}

declare module 'usus/chrome-linux/resources/inspector/network/network_module' {
  declare module.exports: any;
}

declare module 'usus/chrome-linux/resources/inspector/object_ui/object_ui_module' {
  declare module.exports: any;
}

declare module 'usus/chrome-linux/resources/inspector/perf_ui/perf_ui_module' {
  declare module.exports: any;
}

declare module 'usus/chrome-linux/resources/inspector/product_registry_impl/product_registry_impl_module' {
  declare module.exports: any;
}

declare module 'usus/chrome-linux/resources/inspector/product_registry/product_registry_module' {
  declare module.exports: any;
}

declare module 'usus/chrome-linux/resources/inspector/profiler/profiler_module' {
  declare module.exports: any;
}

declare module 'usus/chrome-linux/resources/inspector/protocol/protocol_module' {
  declare module.exports: any;
}

declare module 'usus/chrome-linux/resources/inspector/quick_open/quick_open_module' {
  declare module.exports: any;
}

declare module 'usus/chrome-linux/resources/inspector/resources/resources_module' {
  declare module.exports: any;
}

declare module 'usus/chrome-linux/resources/inspector/sass/sass_module' {
  declare module.exports: any;
}

declare module 'usus/chrome-linux/resources/inspector/screencast/screencast_module' {
  declare module.exports: any;
}

declare module 'usus/chrome-linux/resources/inspector/sdk/sdk_module' {
  declare module.exports: any;
}

declare module 'usus/chrome-linux/resources/inspector/security/security_module' {
  declare module.exports: any;
}

declare module 'usus/chrome-linux/resources/inspector/settings/settings_module' {
  declare module.exports: any;
}

declare module 'usus/chrome-linux/resources/inspector/snippets/snippets_module' {
  declare module.exports: any;
}

declare module 'usus/chrome-linux/resources/inspector/source_frame/source_frame_module' {
  declare module.exports: any;
}

declare module 'usus/chrome-linux/resources/inspector/sources/sources_module' {
  declare module.exports: any;
}

declare module 'usus/chrome-linux/resources/inspector/SupportedCSSProperties' {
  declare module.exports: any;
}

declare module 'usus/chrome-linux/resources/inspector/terminal/terminal_module' {
  declare module.exports: any;
}

declare module 'usus/chrome-linux/resources/inspector/Tests' {
  declare module.exports: any;
}

declare module 'usus/chrome-linux/resources/inspector/text_editor/text_editor_module' {
  declare module.exports: any;
}

declare module 'usus/chrome-linux/resources/inspector/timeline_model/timeline_model_module' {
  declare module.exports: any;
}

declare module 'usus/chrome-linux/resources/inspector/timeline/timeline_module' {
  declare module.exports: any;
}

declare module 'usus/chrome-linux/resources/inspector/toolbox' {
  declare module.exports: any;
}

declare module 'usus/chrome-linux/resources/inspector/unit_test_runner' {
  declare module.exports: any;
}

declare module 'usus/chrome-linux/resources/inspector/workspace_diff/workspace_diff_module' {
  declare module.exports: any;
}

declare module 'usus/dist/bin/commands/render' {
  declare module.exports: any;
}

declare module 'usus/dist/bin/index' {
  declare module.exports: any;
}

declare module 'usus/dist/factories/createConfiguration' {
  declare module.exports: any;
}

declare module 'usus/dist/types' {
  declare module.exports: any;
}

declare module 'usus/dist/usus' {
  declare module.exports: any;
}

declare module 'usus/dist/utilities/normalizeNetworkResourceUrl' {
  declare module.exports: any;
}

declare module 'usus/src/bin/commands/render' {
  declare module.exports: any;
}

declare module 'usus/src/bin/index' {
  declare module.exports: any;
}

declare module 'usus/src/factories/createConfiguration' {
  declare module.exports: any;
}

declare module 'usus/src/types' {
  declare module.exports: any;
}

declare module 'usus/src/usus' {
  declare module.exports: any;
}

declare module 'usus/src/utilities/normalizeNetworkResourceUrl' {
  declare module.exports: any;
}

// Filename aliases
declare module 'usus/chrome-linux/resources/inspector/accessibility/accessibility_module.js' {
  declare module.exports: $Exports<'usus/chrome-linux/resources/inspector/accessibility/accessibility_module'>;
}
declare module 'usus/chrome-linux/resources/inspector/animation/animation_module.js' {
  declare module.exports: $Exports<'usus/chrome-linux/resources/inspector/animation/animation_module'>;
}
declare module 'usus/chrome-linux/resources/inspector/audits/audits_module.js' {
  declare module.exports: $Exports<'usus/chrome-linux/resources/inspector/audits/audits_module'>;
}
declare module 'usus/chrome-linux/resources/inspector/audits2_worker.js' {
  declare module.exports: $Exports<'usus/chrome-linux/resources/inspector/audits2_worker'>;
}
declare module 'usus/chrome-linux/resources/inspector/audits2_worker/audits2_worker_module.js' {
  declare module.exports: $Exports<'usus/chrome-linux/resources/inspector/audits2_worker/audits2_worker_module'>;
}
declare module 'usus/chrome-linux/resources/inspector/audits2/audits2_module.js' {
  declare module.exports: $Exports<'usus/chrome-linux/resources/inspector/audits2/audits2_module'>;
}
declare module 'usus/chrome-linux/resources/inspector/changes/changes_module.js' {
  declare module.exports: $Exports<'usus/chrome-linux/resources/inspector/changes/changes_module'>;
}
declare module 'usus/chrome-linux/resources/inspector/cm_modes/cm_modes_module.js' {
  declare module.exports: $Exports<'usus/chrome-linux/resources/inspector/cm_modes/cm_modes_module'>;
}
declare module 'usus/chrome-linux/resources/inspector/cm/cm_module.js' {
  declare module.exports: $Exports<'usus/chrome-linux/resources/inspector/cm/cm_module'>;
}
declare module 'usus/chrome-linux/resources/inspector/color_picker/color_picker_module.js' {
  declare module.exports: $Exports<'usus/chrome-linux/resources/inspector/color_picker/color_picker_module'>;
}
declare module 'usus/chrome-linux/resources/inspector/console_test_runner/console_test_runner_module.js' {
  declare module.exports: $Exports<'usus/chrome-linux/resources/inspector/console_test_runner/console_test_runner_module'>;
}
declare module 'usus/chrome-linux/resources/inspector/console/console_module.js' {
  declare module.exports: $Exports<'usus/chrome-linux/resources/inspector/console/console_module'>;
}
declare module 'usus/chrome-linux/resources/inspector/cookie_table/cookie_table_module.js' {
  declare module.exports: $Exports<'usus/chrome-linux/resources/inspector/cookie_table/cookie_table_module'>;
}
declare module 'usus/chrome-linux/resources/inspector/data_grid/data_grid_module.js' {
  declare module.exports: $Exports<'usus/chrome-linux/resources/inspector/data_grid/data_grid_module'>;
}
declare module 'usus/chrome-linux/resources/inspector/devices/devices_module.js' {
  declare module.exports: $Exports<'usus/chrome-linux/resources/inspector/devices/devices_module'>;
}
declare module 'usus/chrome-linux/resources/inspector/devtools_compatibility.js' {
  declare module.exports: $Exports<'usus/chrome-linux/resources/inspector/devtools_compatibility'>;
}
declare module 'usus/chrome-linux/resources/inspector/devtools_extension_api.js' {
  declare module.exports: $Exports<'usus/chrome-linux/resources/inspector/devtools_extension_api'>;
}
declare module 'usus/chrome-linux/resources/inspector/diff/diff_module.js' {
  declare module.exports: $Exports<'usus/chrome-linux/resources/inspector/diff/diff_module'>;
}
declare module 'usus/chrome-linux/resources/inspector/elements_test_runner/elements_test_runner_module.js' {
  declare module.exports: $Exports<'usus/chrome-linux/resources/inspector/elements_test_runner/elements_test_runner_module'>;
}
declare module 'usus/chrome-linux/resources/inspector/elements/elements_module.js' {
  declare module.exports: $Exports<'usus/chrome-linux/resources/inspector/elements/elements_module'>;
}
declare module 'usus/chrome-linux/resources/inspector/emulated_devices/emulated_devices_module.js' {
  declare module.exports: $Exports<'usus/chrome-linux/resources/inspector/emulated_devices/emulated_devices_module'>;
}
declare module 'usus/chrome-linux/resources/inspector/event_listeners/event_listeners_module.js' {
  declare module.exports: $Exports<'usus/chrome-linux/resources/inspector/event_listeners/event_listeners_module'>;
}
declare module 'usus/chrome-linux/resources/inspector/formatter_worker.js' {
  declare module.exports: $Exports<'usus/chrome-linux/resources/inspector/formatter_worker'>;
}
declare module 'usus/chrome-linux/resources/inspector/formatter/formatter_module.js' {
  declare module.exports: $Exports<'usus/chrome-linux/resources/inspector/formatter/formatter_module'>;
}
declare module 'usus/chrome-linux/resources/inspector/gonzales/gonzales_module.js' {
  declare module.exports: $Exports<'usus/chrome-linux/resources/inspector/gonzales/gonzales_module'>;
}
declare module 'usus/chrome-linux/resources/inspector/heap_snapshot_model/heap_snapshot_model_module.js' {
  declare module.exports: $Exports<'usus/chrome-linux/resources/inspector/heap_snapshot_model/heap_snapshot_model_module'>;
}
declare module 'usus/chrome-linux/resources/inspector/heap_snapshot_worker.js' {
  declare module.exports: $Exports<'usus/chrome-linux/resources/inspector/heap_snapshot_worker'>;
}
declare module 'usus/chrome-linux/resources/inspector/inline_editor/inline_editor_module.js' {
  declare module.exports: $Exports<'usus/chrome-linux/resources/inspector/inline_editor/inline_editor_module'>;
}
declare module 'usus/chrome-linux/resources/inspector/inspector.js' {
  declare module.exports: $Exports<'usus/chrome-linux/resources/inspector/inspector'>;
}
declare module 'usus/chrome-linux/resources/inspector/InspectorBackendCommands.js' {
  declare module.exports: $Exports<'usus/chrome-linux/resources/inspector/InspectorBackendCommands'>;
}
declare module 'usus/chrome-linux/resources/inspector/integration_test_runner.js' {
  declare module.exports: $Exports<'usus/chrome-linux/resources/inspector/integration_test_runner'>;
}
declare module 'usus/chrome-linux/resources/inspector/layer_viewer/layer_viewer_module.js' {
  declare module.exports: $Exports<'usus/chrome-linux/resources/inspector/layer_viewer/layer_viewer_module'>;
}
declare module 'usus/chrome-linux/resources/inspector/layers/layers_module.js' {
  declare module.exports: $Exports<'usus/chrome-linux/resources/inspector/layers/layers_module'>;
}
declare module 'usus/chrome-linux/resources/inspector/network_priorities/network_priorities_module.js' {
  declare module.exports: $Exports<'usus/chrome-linux/resources/inspector/network_priorities/network_priorities_module'>;
}
declare module 'usus/chrome-linux/resources/inspector/network/network_module.js' {
  declare module.exports: $Exports<'usus/chrome-linux/resources/inspector/network/network_module'>;
}
declare module 'usus/chrome-linux/resources/inspector/object_ui/object_ui_module.js' {
  declare module.exports: $Exports<'usus/chrome-linux/resources/inspector/object_ui/object_ui_module'>;
}
declare module 'usus/chrome-linux/resources/inspector/perf_ui/perf_ui_module.js' {
  declare module.exports: $Exports<'usus/chrome-linux/resources/inspector/perf_ui/perf_ui_module'>;
}
declare module 'usus/chrome-linux/resources/inspector/product_registry_impl/product_registry_impl_module.js' {
  declare module.exports: $Exports<'usus/chrome-linux/resources/inspector/product_registry_impl/product_registry_impl_module'>;
}
declare module 'usus/chrome-linux/resources/inspector/product_registry/product_registry_module.js' {
  declare module.exports: $Exports<'usus/chrome-linux/resources/inspector/product_registry/product_registry_module'>;
}
declare module 'usus/chrome-linux/resources/inspector/profiler/profiler_module.js' {
  declare module.exports: $Exports<'usus/chrome-linux/resources/inspector/profiler/profiler_module'>;
}
declare module 'usus/chrome-linux/resources/inspector/protocol/protocol_module.js' {
  declare module.exports: $Exports<'usus/chrome-linux/resources/inspector/protocol/protocol_module'>;
}
declare module 'usus/chrome-linux/resources/inspector/quick_open/quick_open_module.js' {
  declare module.exports: $Exports<'usus/chrome-linux/resources/inspector/quick_open/quick_open_module'>;
}
declare module 'usus/chrome-linux/resources/inspector/resources/resources_module.js' {
  declare module.exports: $Exports<'usus/chrome-linux/resources/inspector/resources/resources_module'>;
}
declare module 'usus/chrome-linux/resources/inspector/sass/sass_module.js' {
  declare module.exports: $Exports<'usus/chrome-linux/resources/inspector/sass/sass_module'>;
}
declare module 'usus/chrome-linux/resources/inspector/screencast/screencast_module.js' {
  declare module.exports: $Exports<'usus/chrome-linux/resources/inspector/screencast/screencast_module'>;
}
declare module 'usus/chrome-linux/resources/inspector/sdk/sdk_module.js' {
  declare module.exports: $Exports<'usus/chrome-linux/resources/inspector/sdk/sdk_module'>;
}
declare module 'usus/chrome-linux/resources/inspector/security/security_module.js' {
  declare module.exports: $Exports<'usus/chrome-linux/resources/inspector/security/security_module'>;
}
declare module 'usus/chrome-linux/resources/inspector/settings/settings_module.js' {
  declare module.exports: $Exports<'usus/chrome-linux/resources/inspector/settings/settings_module'>;
}
declare module 'usus/chrome-linux/resources/inspector/snippets/snippets_module.js' {
  declare module.exports: $Exports<'usus/chrome-linux/resources/inspector/snippets/snippets_module'>;
}
declare module 'usus/chrome-linux/resources/inspector/source_frame/source_frame_module.js' {
  declare module.exports: $Exports<'usus/chrome-linux/resources/inspector/source_frame/source_frame_module'>;
}
declare module 'usus/chrome-linux/resources/inspector/sources/sources_module.js' {
  declare module.exports: $Exports<'usus/chrome-linux/resources/inspector/sources/sources_module'>;
}
declare module 'usus/chrome-linux/resources/inspector/SupportedCSSProperties.js' {
  declare module.exports: $Exports<'usus/chrome-linux/resources/inspector/SupportedCSSProperties'>;
}
declare module 'usus/chrome-linux/resources/inspector/terminal/terminal_module.js' {
  declare module.exports: $Exports<'usus/chrome-linux/resources/inspector/terminal/terminal_module'>;
}
declare module 'usus/chrome-linux/resources/inspector/Tests.js' {
  declare module.exports: $Exports<'usus/chrome-linux/resources/inspector/Tests'>;
}
declare module 'usus/chrome-linux/resources/inspector/text_editor/text_editor_module.js' {
  declare module.exports: $Exports<'usus/chrome-linux/resources/inspector/text_editor/text_editor_module'>;
}
declare module 'usus/chrome-linux/resources/inspector/timeline_model/timeline_model_module.js' {
  declare module.exports: $Exports<'usus/chrome-linux/resources/inspector/timeline_model/timeline_model_module'>;
}
declare module 'usus/chrome-linux/resources/inspector/timeline/timeline_module.js' {
  declare module.exports: $Exports<'usus/chrome-linux/resources/inspector/timeline/timeline_module'>;
}
declare module 'usus/chrome-linux/resources/inspector/toolbox.js' {
  declare module.exports: $Exports<'usus/chrome-linux/resources/inspector/toolbox'>;
}
declare module 'usus/chrome-linux/resources/inspector/unit_test_runner.js' {
  declare module.exports: $Exports<'usus/chrome-linux/resources/inspector/unit_test_runner'>;
}
declare module 'usus/chrome-linux/resources/inspector/workspace_diff/workspace_diff_module.js' {
  declare module.exports: $Exports<'usus/chrome-linux/resources/inspector/workspace_diff/workspace_diff_module'>;
}
declare module 'usus/dist/bin/commands/render.js' {
  declare module.exports: $Exports<'usus/dist/bin/commands/render'>;
}
declare module 'usus/dist/bin/index.js' {
  declare module.exports: $Exports<'usus/dist/bin/index'>;
}
declare module 'usus/dist/factories/createConfiguration.js' {
  declare module.exports: $Exports<'usus/dist/factories/createConfiguration'>;
}
declare module 'usus/dist/types.js' {
  declare module.exports: $Exports<'usus/dist/types'>;
}
declare module 'usus/dist/usus.js' {
  declare module.exports: $Exports<'usus/dist/usus'>;
}
declare module 'usus/dist/utilities/normalizeNetworkResourceUrl.js' {
  declare module.exports: $Exports<'usus/dist/utilities/normalizeNetworkResourceUrl'>;
}
declare module 'usus/src/bin/commands/render.js' {
  declare module.exports: $Exports<'usus/src/bin/commands/render'>;
}
declare module 'usus/src/bin/index.js' {
  declare module.exports: $Exports<'usus/src/bin/index'>;
}
declare module 'usus/src/factories/createConfiguration.js' {
  declare module.exports: $Exports<'usus/src/factories/createConfiguration'>;
}
declare module 'usus/src/types.js' {
  declare module.exports: $Exports<'usus/src/types'>;
}
declare module 'usus/src/usus.js' {
  declare module.exports: $Exports<'usus/src/usus'>;
}
declare module 'usus/src/utilities/normalizeNetworkResourceUrl.js' {
  declare module.exports: $Exports<'usus/src/utilities/normalizeNetworkResourceUrl'>;
}
