/* eslint-disable */
// this file is auto generated

module.exports = {
  countries: [
    { id: 'afghanistan', name: 'Afghanistan', slug: 'afghanistan' },
    { id: 'aland-islands', name: 'Aland Islands', slug: 'aland-islands' },
    { id: 'albania', name: 'Albania', slug: 'albania' },
    { id: 'algeria', name: 'Algeria', slug: 'algeria' },
    { id: 'american-samoa', name: 'American Samoa', slug: 'american-samoa' },
    { id: 'andorra', name: 'Andorra', slug: 'andorra' },
    { id: 'angola', name: 'Angola', slug: 'angola' },
    { id: 'anguilla', name: 'Anguilla', slug: 'anguilla' },
    { id: 'antarctica', name: 'Antarctica', slug: 'antarctica' },
    {
      id: 'antigua-and-barbuda',
      name: 'Antigua & Barbuda',
      slug: 'antigua-and-barbuda'
    },
    { id: 'argentina', name: 'Argentina', slug: 'argentina' },
    { id: 'armenia', name: 'Armenia', slug: 'armenia' },
    { id: 'aruba', name: 'Aruba', slug: 'aruba' },
    { id: 'australia', name: 'Australia', slug: 'australia' },
    { id: 'austria', name: 'Austria', slug: 'austria' },
    { id: 'azerbaijan', name: 'Azerbaijan', slug: 'azerbaijan' },
    { id: 'bahamas', name: 'Bahamas', slug: 'bahamas' },
    { id: 'bahrain', name: 'Bahrain', slug: 'bahrain' },
    { id: 'bangladesh', name: 'Bangladesh', slug: 'bangladesh' },
    { id: 'barbados', name: 'Barbados', slug: 'barbados' },
    { id: 'belarus', name: 'Belarus', slug: 'belarus' },
    { id: 'belgium', name: 'Belgium', slug: 'belgium' },
    { id: 'belize', name: 'Belize', slug: 'belize' },
    { id: 'benin', name: 'Benin', slug: 'benin' },
    { id: 'bermuda', name: 'Bermuda', slug: 'bermuda' },
    { id: 'bhutan', name: 'Bhutan', slug: 'bhutan' },
    { id: 'bolivia', name: 'Bolivia', slug: 'bolivia' },
    { id: 'bes-islands', name: 'BES Islands', slug: 'bes-islands' },
    {
      id: 'bosnia-and-herzegovina',
      name: 'Bosnia & Herzegovina',
      slug: 'bosnia-and-herzegovina'
    },
    { id: 'botswana', name: 'Botswana', slug: 'botswana' },
    { id: 'bouvet-island', name: 'Bouvet Island', slug: 'bouvet-island' },
    { id: 'brazil', name: 'Brazil', slug: 'brazil' },
    {
      id: 'british-indian-ocean-territory',
      name: 'British Indian Ocean Territory',
      slug: 'british-indian-ocean-territory'
    },
    { id: 'brunei', name: 'Brunei', slug: 'brunei' },
    { id: 'bulgaria', name: 'Bulgaria', slug: 'bulgaria' },
    { id: 'burkina-faso', name: 'Burkina Faso', slug: 'burkina-faso' },
    { id: 'burundi', name: 'Burundi', slug: 'burundi' },
    { id: 'cambodia', name: 'Cambodia', slug: 'cambodia' },
    { id: 'cameroon', name: 'Cameroon', slug: 'cameroon' },
    { id: 'canada', name: 'Canada', slug: 'canada' },
    { id: 'cape-verde', name: 'Cape Verde', slug: 'cape-verde' },
    { id: 'cayman-islands', name: 'Cayman Islands', slug: 'cayman-islands' },
    { id: 'car', name: 'CAR', slug: 'car' },
    { id: 'chad', name: 'Chad', slug: 'chad' },
    { id: 'chile', name: 'Chile', slug: 'chile' },
    { id: 'china', name: 'China', slug: 'china' },
    {
      id: 'christmas-island',
      name: 'Christmas Island',
      slug: 'christmas-island'
    },
    {
      id: 'cocos-keeling-islands',
      name: 'Cocos (Keeling) Islands',
      slug: 'cocos-keeling-islands'
    },
    { id: 'colombia', name: 'Colombia', slug: 'colombia' },
    { id: 'comoros', name: 'Comoros', slug: 'comoros' },
    { id: 'congo', name: 'Congo', slug: 'congo' },
    { id: 'drc', name: 'DRC', slug: 'drc' },
    { id: 'cook-islands', name: 'Cook Islands', slug: 'cook-islands' },
    { id: 'costa-rica', name: 'Costa Rica', slug: 'costa-rica' },
    { id: 'cote-divoire', name: "Côte d'Ivoire", slug: 'cote-divoire' },
    {
      id: 'country-unspecified',
      name: 'Country not specified',
      slug: 'country-unspecified'
    },
    { id: 'croatia', name: 'Croatia', slug: 'croatia' },
    { id: 'cuba', name: 'Cuba', slug: 'cuba' },
    { id: 'curacao', name: 'Curacao', slug: 'curacao' },
    { id: 'cyprus', name: 'Cyprus', slug: 'cyprus' },
    { id: 'czech-republic', name: 'Czech Republic', slug: 'czech-republic' },
    { id: 'denmark', name: 'Denmark', slug: 'denmark' },
    { id: 'djibouti', name: 'Djibouti', slug: 'djibouti' },
    { id: 'dominica', name: 'Dominica', slug: 'dominica' },
    {
      id: 'dominican-republic',
      name: 'Dominican Republic',
      slug: 'dominican-republic'
    },
    { id: 'ecuador', name: 'Ecuador', slug: 'ecuador' },
    { id: 'egypt', name: 'Egypt', slug: 'egypt' },
    { id: 'el-salvador', name: 'El Salvador', slug: 'el-salvador' },
    {
      id: 'equatorial-guinea',
      name: 'Equatorial Guinea',
      slug: 'equatorial-guinea'
    },
    { id: 'eritrea', name: 'Eritrea', slug: 'eritrea' },
    { id: 'estonia', name: 'Estonia', slug: 'estonia' },
    { id: 'ethiopia', name: 'Ethiopia', slug: 'ethiopia' },
    {
      id: 'falkland-islands',
      name: 'Falkland Islands',
      slug: 'falkland-islands'
    },
    { id: 'faroe-islands', name: 'Faroe Islands', slug: 'faroe-islands' },
    { id: 'fiji', name: 'Fiji', slug: 'fiji' },
    { id: 'finland', name: 'Finland', slug: 'finland' },
    { id: 'france', name: 'France', slug: 'france' },
    { id: 'french-guiana', name: 'French Guiana', slug: 'french-guiana' },
    {
      id: 'french-polynesia',
      name: 'French Polynesia',
      slug: 'french-polynesia'
    },
    {
      id: 'french-southern-territories',
      name: 'French Southern Territories',
      slug: 'french-southern-territories'
    },
    { id: 'gabon', name: 'Gabon', slug: 'gabon' },
    { id: 'gambia', name: 'Gambia', slug: 'gambia' },
    { id: 'georgia', name: 'Georgia', slug: 'georgia' },
    { id: 'germany', name: 'Germany', slug: 'germany' },
    { id: 'ghana', name: 'Ghana', slug: 'ghana' },
    { id: 'gibraltar', name: 'Gibraltar', slug: 'gibraltar' },
    { id: 'greece', name: 'Greece', slug: 'greece' },
    { id: 'greenland', name: 'Greenland', slug: 'greenland' },
    { id: 'grenada', name: 'Grenada', slug: 'grenada' },
    { id: 'guadeloupe', name: 'Guadeloupe', slug: 'guadeloupe' },
    { id: 'guam', name: 'Guam', slug: 'guam' },
    { id: 'guatemala', name: 'Guatemala', slug: 'guatemala' },
    { id: 'guernsey', name: 'Guernsey', slug: 'guernsey' },
    { id: 'guinea', name: 'Guinea', slug: 'guinea' },
    { id: 'guinea-bissau', name: 'Guinea-Bissau', slug: 'guinea-bissau' },
    { id: 'guyana', name: 'Guyana', slug: 'guyana' },
    { id: 'haiti', name: 'Haiti', slug: 'haiti' },
    {
      id: 'heard-island-and-mcdonald-islands',
      name: 'Heard Island & McDonald Islands',
      slug: 'heard-island-and-mcdonald-islands'
    },
    {
      id: 'holy-see-vatican-city-state',
      name: 'Holy See (Vatican City State)',
      slug: 'holy-see-vatican-city-state'
    },
    { id: 'honduras', name: 'Honduras', slug: 'honduras' },
    { id: 'hong-kong', name: 'Hong Kong', slug: 'hong-kong' },
    { id: 'hungary', name: 'Hungary', slug: 'hungary' },
    { id: 'iceland', name: 'Iceland', slug: 'iceland' },
    { id: 'india', name: 'India', slug: 'india' },
    { id: 'indonesia', name: 'Indonesia', slug: 'indonesia' },
    { id: 'iran', name: 'Iran', slug: 'iran' },
    { id: 'iraq', name: 'Iraq', slug: 'iraq' },
    { id: 'ireland', name: 'Ireland', slug: 'ireland' },
    { id: 'isle-of-man', name: 'Isle of Man', slug: 'isle-of-man' },
    { id: 'israel', name: 'Israel', slug: 'israel' },
    { id: 'italy', name: 'Italy', slug: 'italy' },
    { id: 'jamaica', name: 'Jamaica', slug: 'jamaica' },
    { id: 'japan', name: 'Japan', slug: 'japan' },
    { id: 'jersey', name: 'Jersey', slug: 'jersey' },
    { id: 'jordan', name: 'Jordan', slug: 'jordan' },
    { id: 'kazakhstan', name: 'Kazakhstan', slug: 'kazakhstan' },
    { id: 'kenya', name: 'Kenya', slug: 'kenya' },
    { id: 'kiribati', name: 'Kiribati', slug: 'kiribati' },
    { id: 'north-korea', name: 'North Korea', slug: 'north-korea' },
    { id: 'south-korea', name: 'Korea', slug: 'south-korea' },
    { id: 'kosovo', name: 'Kosovo', slug: 'kosovo' },
    { id: 'kuwait', name: 'Kuwait', slug: 'kuwait' },
    { id: 'kyrgyzstan', name: 'Kyrgyzstan', slug: 'kyrgyzstan' },
    { id: 'lao', name: 'Lao', slug: 'lao' },
    { id: 'latvia', name: 'Latvia', slug: 'latvia' },
    { id: 'lebanon', name: 'Lebanon', slug: 'lebanon' },
    { id: 'lesotho', name: 'Lesotho', slug: 'lesotho' },
    { id: 'liberia', name: 'Liberia', slug: 'liberia' },
    { id: 'libya', name: 'Libya', slug: 'libya' },
    { id: 'liechtenstein', name: 'Liechtenstein', slug: 'liechtenstein' },
    { id: 'lithuania', name: 'Lithuania', slug: 'lithuania' },
    { id: 'luxembourg', name: 'Luxembourg', slug: 'luxembourg' },
    { id: 'macao', name: 'Macao', slug: 'macao' },
    { id: 'macedonia', name: 'Macedonia', slug: 'macedonia' },
    { id: 'madagascar', name: 'Madagascar', slug: 'madagascar' },
    { id: 'malawi', name: 'Malawi', slug: 'malawi' },
    { id: 'malaysia', name: 'Malaysia', slug: 'malaysia' },
    { id: 'maldives', name: 'Maldives', slug: 'maldives' },
    { id: 'mali', name: 'Mali', slug: 'mali' },
    { id: 'malta', name: 'Malta', slug: 'malta' },
    {
      id: 'marshall-islands',
      name: 'Marshall Islands',
      slug: 'marshall-islands'
    },
    { id: 'martinique', name: 'Martinique', slug: 'martinique' },
    { id: 'mauritania', name: 'Mauritania', slug: 'mauritania' },
    { id: 'mauritius', name: 'Mauritius', slug: 'mauritius' },
    { id: 'mayotte', name: 'Mayotte', slug: 'mayotte' },
    { id: 'mexico', name: 'Mexico', slug: 'mexico' },
    { id: 'micronesia', name: 'Micronesia', slug: 'micronesia' },
    { id: 'moldova', name: 'Moldova', slug: 'moldova' },
    { id: 'monaco', name: 'Monaco', slug: 'monaco' },
    { id: 'mongolia', name: 'Mongolia', slug: 'mongolia' },
    { id: 'montenegro', name: 'Montenegro', slug: 'montenegro' },
    { id: 'montserrat', name: 'Montserrat', slug: 'montserrat' },
    { id: 'morocco', name: 'Morocco', slug: 'morocco' },
    { id: 'mozambique', name: 'Mozambique', slug: 'mozambique' },
    { id: 'myanmar', name: 'Myanmar', slug: 'myanmar' },
    { id: 'namibia', name: 'Namibia', slug: 'namibia' },
    { id: 'nauru', name: 'Nauru', slug: 'nauru' },
    { id: 'nepal', name: 'Nepal', slug: 'nepal' },
    { id: 'netherlands', name: 'Netherlands', slug: 'netherlands' },
    {
      id: 'netherlands-antilles',
      name: 'Netherlands Antilles',
      slug: 'netherlands-antilles'
    },
    { id: 'new-caledonia', name: 'New Caledonia', slug: 'new-caledonia' },
    { id: 'new-zealand', name: 'New Zealand', slug: 'new-zealand' },
    { id: 'nicaragua', name: 'Nicaragua', slug: 'nicaragua' },
    { id: 'niger', name: 'Niger', slug: 'niger' },
    { id: 'nigeria', name: 'Nigeria', slug: 'nigeria' },
    { id: 'niue', name: 'Niue', slug: 'niue' },
    { id: 'norfolk-island', name: 'Norfolk Island', slug: 'norfolk-island' },
    {
      id: 'northern-mariana-islands',
      name: 'Northern Mariana Islands',
      slug: 'northern-mariana-islands'
    },
    { id: 'norway', name: 'Norway', slug: 'norway' },
    { id: 'oman', name: 'Oman', slug: 'oman' },
    { id: 'pakistan', name: 'Pakistan', slug: 'pakistan' },
    { id: 'palau', name: 'Palau', slug: 'palau' },
    { id: 'palestine', name: 'Palestine', slug: 'palestine' },
    { id: 'panama', name: 'Panama', slug: 'panama' },
    {
      id: 'papua-new-guinea',
      name: 'Papua New Guinea',
      slug: 'papua-new-guinea'
    },
    { id: 'paraguay', name: 'Paraguay', slug: 'paraguay' },
    { id: 'peru', name: 'Peru', slug: 'peru' },
    { id: 'philippines', name: 'Philippines', slug: 'philippines' },
    { id: 'pitcairn', name: 'Pitcairn', slug: 'pitcairn' },
    { id: 'poland', name: 'Poland', slug: 'poland' },
    { id: 'portugal', name: 'Portugal', slug: 'portugal' },
    { id: 'puerto-rico', name: 'Puerto Rico', slug: 'puerto-rico' },
    { id: 'qatar', name: 'Qatar', slug: 'qatar' },
    { id: 'réunion', name: 'Reunion', slug: 'réunion' },
    { id: 'romania', name: 'Romania', slug: 'romania' },
    {
      id: 'russian-federation',
      name: 'Russian Federation',
      slug: 'russian-federation'
    },
    { id: 'rwanda', name: 'Rwanda', slug: 'rwanda' },
    {
      id: 'saint-barthelemy',
      name: 'Saint Barthelemy',
      slug: 'saint-barthelemy'
    },
    {
      id: 'saint-helena-ascension-and-tristan-da-cunha',
      name: 'Saint Helena, Ascension & Tristan da Cunha',
      slug: 'saint-helena-ascension-and-tristan-da-cunha'
    },
    {
      id: 'saint-kitts-and-nevis',
      name: 'Saint Kitts and Nevis',
      slug: 'saint-kitts-and-nevis'
    },
    { id: 'saint-lucia', name: 'Saint Lucia', slug: 'saint-lucia' },
    { id: 'saint-martin', name: 'Saint Martin', slug: 'saint-martin' },
    {
      id: 'saint-pierre-and-miquelon',
      name: 'Saint Pierre & Miquelon',
      slug: 'saint-pierre-and-miquelon'
    },
    {
      id: 'saint-vincent-and-the-grenadines',
      name: 'Saint Vincent & the Grenadines',
      slug: 'saint-vincent-and-the-grenadines'
    },
    { id: 'samoa', name: 'Samoa', slug: 'samoa' },
    { id: 'san-marino', name: 'San Marino', slug: 'san-marino' },
    {
      id: 'sao-tome-and-principe',
      name: 'Sao Tome & Principe',
      slug: 'sao-tome-and-principe'
    },
    { id: 'saudi-arabia', name: 'Saudi Arabia', slug: 'saudi-arabia' },
    { id: 'senegal', name: 'Senegal', slug: 'senegal' },
    { id: 'serbia', name: 'Serbia', slug: 'serbia' },
    { id: 'seychelles', name: 'Seychelles', slug: 'seychelles' },
    { id: 'sierra-leone', name: 'Sierra Leone', slug: 'sierra-leone' },
    { id: 'singapore', name: 'Singapore', slug: 'singapore' },
    {
      id: 'sint-maarten-dutch-part',
      name: 'Sint Maarten (Dutch part)',
      slug: 'sint-maarten-dutch-part'
    },
    { id: 'slovakia', name: 'Slovak Republic', slug: 'slovakia' },
    { id: 'slovenia', name: 'Slovenia', slug: 'slovenia' },
    { id: 'solomon-islands', name: 'Solomon Islands', slug: 'solomon-islands' },
    { id: 'somalia', name: 'Somalia', slug: 'somalia' },
    { id: 'south-africa', name: 'South Africa', slug: 'south-africa' },
    {
      id: 'south-georgia-and-the-south-sandwich-islands',
      name: 'South Georgia & the South Sandwich Islands',
      slug: 'south-georgia-and-the-south-sandwich-islands'
    },
    { id: 'south-sudan', name: 'South Sudan', slug: 'south-sudan' },
    { id: 'spain', name: 'Spain', slug: 'spain' },
    { id: 'sri-lanka', name: 'Sri Lanka', slug: 'sri-lanka' },
    { id: 'sudan', name: 'Sudan', slug: 'sudan' },
    { id: 'suriname', name: 'Suriname', slug: 'suriname' },
    {
      id: 'svalbard-and-jan-mayen',
      name: 'Svalbard & Jan Mayen',
      slug: 'svalbard-and-jan-mayen'
    },
    { id: 'swaziland', name: 'Swaziland', slug: 'swaziland' },
    { id: 'sweden', name: 'Sweden', slug: 'sweden' },
    { id: 'switzerland', name: 'Switzerland', slug: 'switzerland' },
    { id: 'syria', name: 'Syria', slug: 'syria' },
    { id: 'taiwan', name: 'Taiwan', slug: 'taiwan' },
    { id: 'tajikistan', name: 'Tajikistan', slug: 'tajikistan' },
    { id: 'tanzania', name: 'Tanzania', slug: 'tanzania' },
    { id: 'thailand', name: 'Thailand', slug: 'thailand' },
    { id: 'timor-leste', name: 'Timor-Leste', slug: 'timor-leste' },
    { id: 'togo', name: 'Togo', slug: 'togo' },
    { id: 'tokelau', name: 'Tokelau', slug: 'tokelau' },
    { id: 'tonga', name: 'Tonga', slug: 'tonga' },
    {
      id: 'trinidad-and-tobago',
      name: 'Trinidad & Tobago',
      slug: 'trinidad-and-tobago'
    },
    { id: 'tunisia', name: 'Tunisia', slug: 'tunisia' },
    { id: 'turkey', name: 'Turkey', slug: 'turkey' },
    { id: 'turkmenistan', name: 'Turkmenistan', slug: 'turkmenistan' },
    {
      id: 'turks-and-caicos-islands',
      name: 'Turks & Caicos Islands',
      slug: 'turks-and-caicos-islands'
    },
    { id: 'tuvalu', name: 'Tuvalu', slug: 'tuvalu' },
    { id: 'uganda', name: 'Uganda', slug: 'uganda' },
    { id: 'united-kingdom', name: 'United Kingdom', slug: 'united-kingdom' },
    { id: 'ukraine', name: 'Ukraine', slug: 'ukraine' },
    { id: 'uae', name: 'UAE', slug: 'uae' },
    { id: 'usa', name: 'United States', slug: 'usa' },
    {
      id: 'united-states-minor-outlying-islands',
      name: 'United States Minor Outlying Islands',
      slug: 'united-states-minor-outlying-islands'
    },
    { id: 'uruguay', name: 'Uruguay', slug: 'uruguay' },
    { id: 'uzbekistan', name: 'Uzbekistan', slug: 'uzbekistan' },
    { id: 'vanuatu', name: 'Vanuatu', slug: 'vanuatu' },
    { id: 'venezuela', name: 'Venezuela', slug: 'venezuela' },
    { id: 'viet-nam', name: 'Viet Nam', slug: 'viet-nam' },
    {
      id: 'virgin-islands-gb',
      name: 'Virgin Islands (GB)',
      slug: 'virgin-islands-gb'
    },
    {
      id: 'virgin-islands-us',
      name: 'Virgin Islands (US)',
      slug: 'virgin-islands-us'
    },
    {
      id: 'wallis-and-futuna',
      name: 'Wallis & Futuna',
      slug: 'wallis-and-futuna'
    },
    { id: 'western-sahara', name: 'Western Sahara', slug: 'western-sahara' },
    { id: 'yemen', name: 'Yemen', slug: 'yemen' },
    { id: 'zambia', name: 'Zambia', slug: 'zambia' },
    { id: 'zimbabwe', name: 'Zimbabwe', slug: 'zimbabwe' }
  ]
};
