/* eslint-disable */
// this file is auto generated

module.exports = {
  countries: [
    { id: 'afghanistan', name: 'Afghanistan' },
    { id: 'aland-islands', name: 'Aland Islands' },
    { id: 'albania', name: 'Albania' },
    { id: 'algeria', name: 'Algeria' },
    { id: 'american-samoa', name: 'American Samoa' },
    { id: 'andorra', name: 'Andorra' },
    { id: 'angola', name: 'Angola' },
    { id: 'anguilla', name: 'Anguilla' },
    { id: 'antarctica', name: 'Antarctica' },
    { id: 'antigua-and-barbuda', name: 'Antigua & Barbuda' },
    { id: 'argentina', name: 'Argentina' },
    { id: 'armenia', name: 'Armenia' },
    { id: 'aruba', name: 'Aruba' },
    { id: 'australia', name: 'Australia' },
    { id: 'austria', name: 'Austria' },
    { id: 'azerbaijan', name: 'Azerbaijan' },
    { id: 'bahamas', name: 'Bahamas' },
    { id: 'bahrain', name: 'Bahrain' },
    { id: 'bangladesh', name: 'Bangladesh' },
    { id: 'barbados', name: 'Barbados' },
    { id: 'belarus', name: 'Belarus' },
    { id: 'belgium', name: 'Belgium' },
    { id: 'belize', name: 'Belize' },
    { id: 'benin', name: 'Benin' },
    { id: 'bermuda', name: 'Bermuda' },
    { id: 'bhutan', name: 'Bhutan' },
    { id: 'bolivia', name: 'Bolivia' },
    { id: 'bes-islands', name: 'BES Islands' },
    { id: 'bosnia-and-herzegovina', name: 'Bosnia & Herzegovina' },
    { id: 'botswana', name: 'Botswana' },
    { id: 'bouvet-island', name: 'Bouvet Island' },
    { id: 'brazil', name: 'Brazil' },
    {
      id: 'british-indian-ocean-territory',
      name: 'British Indian Ocean Territory'
    },
    { id: 'brunei', name: 'Brunei' },
    { id: 'bulgaria', name: 'Bulgaria' },
    { id: 'burkina-faso', name: 'Burkina Faso' },
    { id: 'burundi', name: 'Burundi' },
    { id: 'cambodia', name: 'Cambodia' },
    { id: 'cameroon', name: 'Cameroon' },
    { id: 'canada', name: 'Canada' },
    { id: 'cape-verde', name: 'Cape Verde' },
    { id: 'cayman-islands', name: 'Cayman Islands' },
    { id: 'car', name: 'CAR' },
    { id: 'chad', name: 'Chad' },
    { id: 'chile', name: 'Chile' },
    { id: 'china', name: 'China' },
    { id: 'christmas-island', name: 'Christmas Island' },
    { id: 'cocos-keeling-islands', name: 'Cocos (Keeling) Islands' },
    { id: 'colombia', name: 'Colombia' },
    { id: 'comoros', name: 'Comoros' },
    { id: 'congo', name: 'Congo' },
    { id: 'drc', name: 'DRC' },
    { id: 'cook-islands', name: 'Cook Islands' },
    { id: 'costa-rica', name: 'Costa Rica' },
    { id: 'cote-divoire', name: "Côte d'Ivoire" },
    { id: 'country-unspecified', name: 'Country not specified' },
    { id: 'croatia', name: 'Croatia' },
    { id: 'cuba', name: 'Cuba' },
    { id: 'curacao', name: 'Curacao' },
    { id: 'cyprus', name: 'Cyprus' },
    { id: 'czech-republic', name: 'Czech Republic' },
    { id: 'denmark', name: 'Denmark' },
    { id: 'djibouti', name: 'Djibouti' },
    { id: 'dominica', name: 'Dominica' },
    { id: 'dominican-republic', name: 'Dominican Republic' },
    { id: 'ecuador', name: 'Ecuador' },
    { id: 'egypt', name: 'Egypt' },
    { id: 'el-salvador', name: 'El Salvador' },
    { id: 'equatorial-guinea', name: 'Equatorial Guinea' },
    { id: 'eritrea', name: 'Eritrea' },
    { id: 'estonia', name: 'Estonia' },
    { id: 'ethiopia', name: 'Ethiopia' },
    { id: 'falkland-islands', name: 'Falkland Islands' },
    { id: 'faroe-islands', name: 'Faroe Islands' },
    { id: 'fiji', name: 'Fiji' },
    { id: 'finland', name: 'Finland' },
    { id: 'france', name: 'France' },
    { id: 'french-guiana', name: 'French Guiana' },
    { id: 'french-polynesia', name: 'French Polynesia' },
    { id: 'french-southern-territories', name: 'French Southern Territories' },
    { id: 'gabon', name: 'Gabon' },
    { id: 'gambia', name: 'Gambia' },
    { id: 'georgia', name: 'Georgia' },
    { id: 'germany', name: 'Germany' },
    { id: 'ghana', name: 'Ghana' },
    { id: 'gibraltar', name: 'Gibraltar' },
    { id: 'greece', name: 'Greece' },
    { id: 'greenland', name: 'Greenland' },
    { id: 'grenada', name: 'Grenada' },
    { id: 'guadeloupe', name: 'Guadeloupe' },
    { id: 'guam', name: 'Guam' },
    { id: 'guatemala', name: 'Guatemala' },
    { id: 'guernsey', name: 'Guernsey' },
    { id: 'guinea', name: 'Guinea' },
    { id: 'guinea-bissau', name: 'Guinea-Bissau' },
    { id: 'guyana', name: 'Guyana' },
    { id: 'haiti', name: 'Haiti' },
    {
      id: 'heard-island-and-mcdonald-islands',
      name: 'Heard Island & McDonald Islands'
    },
    {
      id: 'holy-see-vatican-city-state',
      name: 'Holy See (Vatican City State)'
    },
    { id: 'honduras', name: 'Honduras' },
    { id: 'hong-kong', name: 'Hong Kong' },
    { id: 'hungary', name: 'Hungary' },
    { id: 'iceland', name: 'Iceland' },
    { id: 'india', name: 'India' },
    { id: 'indonesia', name: 'Indonesia' },
    { id: 'iran', name: 'Iran' },
    { id: 'iraq', name: 'Iraq' },
    { id: 'ireland', name: 'Ireland' },
    { id: 'isle-of-man', name: 'Isle of Man' },
    { id: 'israel', name: 'Israel' },
    { id: 'italy', name: 'Italy' },
    { id: 'jamaica', name: 'Jamaica' },
    { id: 'japan', name: 'Japan' },
    { id: 'jersey', name: 'Jersey' },
    { id: 'jordan', name: 'Jordan' },
    { id: 'kazakhstan', name: 'Kazakhstan' },
    { id: 'kenya', name: 'Kenya' },
    { id: 'kiribati', name: 'Kiribati' },
    { id: 'north-korea', name: 'North Korea' },
    { id: 'south-korea', name: 'Korea' },
    { id: 'kosovo', name: 'Kosovo' },
    { id: 'kuwait', name: 'Kuwait' },
    { id: 'kyrgyzstan', name: 'Kyrgyzstan' },
    { id: 'lao', name: 'Lao' },
    { id: 'latvia', name: 'Latvia' },
    { id: 'lebanon', name: 'Lebanon' },
    { id: 'lesotho', name: 'Lesotho' },
    { id: 'liberia', name: 'Liberia' },
    { id: 'libya', name: 'Libya' },
    { id: 'liechtenstein', name: 'Liechtenstein' },
    { id: 'lithuania', name: 'Lithuania' },
    { id: 'luxembourg', name: 'Luxembourg' },
    { id: 'macao', name: 'Macao' },
    { id: 'macedonia', name: 'Macedonia' },
    { id: 'madagascar', name: 'Madagascar' },
    { id: 'malawi', name: 'Malawi' },
    { id: 'malaysia', name: 'Malaysia' },
    { id: 'maldives', name: 'Maldives' },
    { id: 'mali', name: 'Mali' },
    { id: 'malta', name: 'Malta' },
    { id: 'marshall-islands', name: 'Marshall Islands' },
    { id: 'martinique', name: 'Martinique' },
    { id: 'mauritania', name: 'Mauritania' },
    { id: 'mauritius', name: 'Mauritius' },
    { id: 'mayotte', name: 'Mayotte' },
    { id: 'mexico', name: 'Mexico' },
    { id: 'micronesia', name: 'Micronesia' },
    { id: 'moldova', name: 'Moldova' },
    { id: 'monaco', name: 'Monaco' },
    { id: 'mongolia', name: 'Mongolia' },
    { id: 'montenegro', name: 'Montenegro' },
    { id: 'montserrat', name: 'Montserrat' },
    { id: 'morocco', name: 'Morocco' },
    { id: 'mozambique', name: 'Mozambique' },
    { id: 'myanmar', name: 'Myanmar' },
    { id: 'namibia', name: 'Namibia' },
    { id: 'nauru', name: 'Nauru' },
    { id: 'nepal', name: 'Nepal' },
    { id: 'netherlands', name: 'Netherlands' },
    { id: 'netherlands-antilles', name: 'Netherlands Antilles' },
    { id: 'new-caledonia', name: 'New Caledonia' },
    { id: 'new-zealand', name: 'New Zealand' },
    { id: 'nicaragua', name: 'Nicaragua' },
    { id: 'niger', name: 'Niger' },
    { id: 'nigeria', name: 'Nigeria' },
    { id: 'niue', name: 'Niue' },
    { id: 'norfolk-island', name: 'Norfolk Island' },
    { id: 'northern-mariana-islands', name: 'Northern Mariana Islands' },
    { id: 'norway', name: 'Norway' },
    { id: 'oman', name: 'Oman' },
    { id: 'pakistan', name: 'Pakistan' },
    { id: 'palau', name: 'Palau' },
    { id: 'palestine', name: 'Palestine' },
    { id: 'panama', name: 'Panama' },
    { id: 'papua-new-guinea', name: 'Papua New Guinea' },
    { id: 'paraguay', name: 'Paraguay' },
    { id: 'peru', name: 'Peru' },
    { id: 'philippines', name: 'Philippines' },
    { id: 'pitcairn', name: 'Pitcairn' },
    { id: 'poland', name: 'Poland' },
    { id: 'portugal', name: 'Portugal' },
    { id: 'puerto-rico', name: 'Puerto Rico' },
    { id: 'qatar', name: 'Qatar' },
    { id: 'réunion', name: 'Reunion' },
    { id: 'romania', name: 'Romania' },
    { id: 'russian-federation', name: 'Russian Federation' },
    { id: 'rwanda', name: 'Rwanda' },
    { id: 'saint-barthelemy', name: 'Saint Barthelemy' },
    {
      id: 'saint-helena-ascension-and-tristan-da-cunha',
      name: 'Saint Helena, Ascension & Tristan da Cunha'
    },
    { id: 'saint-kitts-and-nevis', name: 'Saint Kitts and Nevis' },
    { id: 'saint-lucia', name: 'Saint Lucia' },
    { id: 'saint-martin', name: 'Saint Martin' },
    { id: 'saint-pierre-and-miquelon', name: 'Saint Pierre & Miquelon' },
    {
      id: 'saint-vincent-and-the-grenadines',
      name: 'Saint Vincent & the Grenadines'
    },
    { id: 'samoa', name: 'Samoa' },
    { id: 'san-marino', name: 'San Marino' },
    { id: 'sao-tome-and-principe', name: 'Sao Tome & Principe' },
    { id: 'saudi-arabia', name: 'Saudi Arabia' },
    { id: 'senegal', name: 'Senegal' },
    { id: 'serbia', name: 'Serbia' },
    { id: 'seychelles', name: 'Seychelles' },
    { id: 'sierra-leone', name: 'Sierra Leone' },
    { id: 'singapore', name: 'Singapore' },
    { id: 'sint-maarten-dutch-part', name: 'Sint Maarten (Dutch part)' },
    { id: 'slovakia', name: 'Slovak Republic' },
    { id: 'slovenia', name: 'Slovenia' },
    { id: 'solomon-islands', name: 'Solomon Islands' },
    { id: 'somalia', name: 'Somalia' },
    { id: 'south-africa', name: 'South Africa' },
    {
      id: 'south-georgia-and-the-south-sandwich-islands',
      name: 'South Georgia & the South Sandwich Islands'
    },
    { id: 'south-sudan', name: 'South Sudan' },
    { id: 'spain', name: 'Spain' },
    { id: 'sri-lanka', name: 'Sri Lanka' },
    { id: 'sudan', name: 'Sudan' },
    { id: 'suriname', name: 'Suriname' },
    { id: 'svalbard-and-jan-mayen', name: 'Svalbard & Jan Mayen' },
    { id: 'swaziland', name: 'Swaziland' },
    { id: 'sweden', name: 'Sweden' },
    { id: 'switzerland', name: 'Switzerland' },
    { id: 'syria', name: 'Syria' },
    { id: 'taiwan', name: 'Taiwan' },
    { id: 'tajikistan', name: 'Tajikistan' },
    { id: 'tanzania', name: 'Tanzania' },
    { id: 'thailand', name: 'Thailand' },
    { id: 'timor-leste', name: 'Timor-Leste' },
    { id: 'togo', name: 'Togo' },
    { id: 'tokelau', name: 'Tokelau' },
    { id: 'tonga', name: 'Tonga' },
    { id: 'trinidad-and-tobago', name: 'Trinidad & Tobago' },
    { id: 'tunisia', name: 'Tunisia' },
    { id: 'turkey', name: 'Turkey' },
    { id: 'turkmenistan', name: 'Turkmenistan' },
    { id: 'turks-and-caicos-islands', name: 'Turks & Caicos Islands' },
    { id: 'tuvalu', name: 'Tuvalu' },
    { id: 'uganda', name: 'Uganda' },
    { id: 'united-kingdom', name: 'United Kingdom' },
    { id: 'ukraine', name: 'Ukraine' },
    { id: 'uae', name: 'UAE' },
    { id: 'usa', name: 'United States' },
    {
      id: 'united-states-minor-outlying-islands',
      name: 'United States Minor Outlying Islands'
    },
    { id: 'uruguay', name: 'Uruguay' },
    { id: 'uzbekistan', name: 'Uzbekistan' },
    { id: 'vanuatu', name: 'Vanuatu' },
    { id: 'venezuela', name: 'Venezuela' },
    { id: 'viet-nam', name: 'Viet Nam' },
    { id: 'virgin-islands-gb', name: 'Virgin Islands (GB)' },
    { id: 'virgin-islands-us', name: 'Virgin Islands (US)' },
    { id: 'wallis-and-futuna', name: 'Wallis & Futuna' },
    { id: 'western-sahara', name: 'Western Sahara' },
    { id: 'yemen', name: 'Yemen' },
    { id: 'zambia', name: 'Zambia' },
    { id: 'zimbabwe', name: 'Zimbabwe' }
  ]
};
