const data = {
  regionalRankings: {
    flags: false,
    top: [
      { number: 1, name: 'Luuka', value: '17.13%' },
      { number: 2, name: 'Wakiso', value: '17.2%' },
      { number: 3, name: 'Jinja', value: '16.4%' },
      { number: 4, name: 'Buikwe', value: '15.1%' },
      { number: 5, name: 'Moroto', value: '10.7%' },
      { number: 6, name: 'Mbarara', value: '9.8%' },
      { number: 7, name: 'Mbale', value: '9.6%' },
      { number: 8, name: 'Mukono', value: '9.5%' },
      { number: 9, name: 'Gulu', value: '9.%' },
      { number: 10, name: 'Hoima', value: '8.5%' },
    ],
    bottom: [
      { number: 101, name: 'Kumi', value: '1.4%' },
      { number: 102, name: 'Apac', value: '1.3%' },
      { number: 103, name: 'Maracha', value: '1.1%' },
      { number: 104, name: 'Butambala', value: '1.1%' },
      { number: 105, name: 'Bukwo', value: '1.1%' },
      { number: 106, name: 'Bukomansimbi', value: '1%' },
      { number: 107, name: 'Otuke', value: '1%' },
      { number: 108, name: 'Luwero', value: '0.9%' },
      { number: 109, name: 'Kubuku', value: '0.9%' },
      { number: 110, name: 'Bundibugyo', value: '0.9%' },
    ],
  },
  tabOptions: {
    districtPublicResources: [
      { key: 0, value: 'Agriculture allocation as a % of total expenditure' },
      { key: 1, value: 'Donor funds' },
      { key: 2, value: 'Education allocation as a % of total expenditure' },
      { key: 3, value: 'Health allocation as a % of total expenditure' },
      { key: 4, value: 'Locally raised revenues' },
    ],
    poverty: [
      { key: 0, value: 'Decent standard of living score' },
      { key: 1, value: 'Poverty headcount' },
      { key: 2, value: 'Life expectancy' },
    ],
    education: [
      {
        key: 0,
        value: 'Secondary pupils with adequate sitting and writing space (government schools)',
      },
      { key: 1, value: 'Secondary pupil-teacher ratio (government schools)' },
      { key: 2, value: 'Secondary pupils with adequate sitting and writing space (total)' },
      { key: 3, value: 'Primary education spending per child' },
      { key: 4, value: 'Secondary net enrolment rate' },
      { key: 5, value: 'Primary education donor spending per child' },
      { key: 6, value: 'Primary pupil to teacher ratio-all schools' },
      { key: 7, value: 'Primary pupils with adequate sitting and writing space-all schools (%)' },
      {
        key: 8,
        value: 'Primary pupils with adequate sitting and writing space-government schools (%)',
      },
      { key: 9, value: 'Primary net enrolment rate' },
      { key: 10, value: 'Primary leaving exam performance index' },
      { key: 10, value: 'Secondary pupil-teacher ratio (total)' },
    ],
    health: [
      { key: 0, value: 'District league table overall score' },
      { key: 1, value: 'HMIS reporting score' },
      { key: 2, value: 'Approved posts that are filled (%)' },
      { key: 3, value: 'Tuberculosis treatment success rate' },
      { key: 4, value: 'Diphtheria treatment coverage rate' },
      { key: 5, value: 'Tetanus vaccine coverage rate' },
      { key: 6, value: 'Antenatal care coverage rate' },
      { key: 7, value: 'Primary health spending per person' },
    ],
    population: [
      { key: 0, value: 'Average household size' },
      { key: 1, value: 'Population density (per sq km)' },
      { key: 2, value: 'Urban population (%)' },
      { key: 3, value: 'Average dependency ratio' },
      { key: 4, value: 'Total population' },
    ],
    waterandSanitation: [
      { key: 0, value: 'Rural access to safe water (%)' },
      { key: 1, value: 'Rural water source functionality (%)' },
      { key: 2, value: 'Functioning water source committees (%)' },
      { key: 3, value: 'Household sanitation coverage (%)' },
      { key: 4, value: 'District WASH performance score' },
    ],
  },
};
export default data;
