// flow-typed signature: 07a0375718e5543a8a7a8ab63f313c96
// flow-typed version: <<STUB>>/@devinit/charts_v1.1.4/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@devinit/charts'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */
declare module '@devinit/charts/lib' {
  declare module.exports: any;
}

declare module '@devinit/charts' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@devinit/charts/dist/di-charts.min' {
  declare module.exports: any;
}

declare module '@devinit/charts/lib/charts/area' {
  declare module.exports: any;
}

declare module '@devinit/charts/lib/charts/bar' {
  declare module.exports: any;
}

declare module '@devinit/charts/lib/charts/bubble' {
  declare module.exports: any;
}

declare module '@devinit/charts/lib/charts/clustered-bar' {
  declare module.exports: any;
}

declare module '@devinit/charts/lib/charts/compound-treemap' {
  declare module.exports: any;
}

declare module '@devinit/charts/lib/charts/full-stacked-area' {
  declare module.exports: any;
}

declare module '@devinit/charts/lib/charts/full-stacked-bar' {
  declare module.exports: any;
}

declare module '@devinit/charts/lib/charts/line' {
  declare module.exports: any;
}

declare module '@devinit/charts/lib/charts/partition' {
  declare module.exports: any;
}

declare module '@devinit/charts/lib/charts/pie' {
  declare module.exports: any;
}

declare module '@devinit/charts/lib/charts/stacked-area' {
  declare module.exports: any;
}

declare module '@devinit/charts/lib/charts/stacked-bar' {
  declare module.exports: any;
}

declare module '@devinit/charts/lib/charts/treemap' {
  declare module.exports: any;
}

declare module '@devinit/charts/lib/factories/createAxis' {
  declare module.exports: any;
}

declare module '@devinit/charts/lib/factories/createCircularChart' {
  declare module.exports: any;
}

declare module '@devinit/charts/lib/factories/createDataset' {
  declare module.exports: any;
}

declare module '@devinit/charts/lib/factories/createGrid' {
  declare module.exports: any;
}

declare module '@devinit/charts/lib/factories/createLegend' {
  declare module.exports: any;
}

declare module '@devinit/charts/lib/factories/createLinearChart' {
  declare module.exports: any;
}

declare module '@devinit/charts/lib/factories/createScale' {
  declare module.exports: any;
}

declare module '@devinit/charts/lib/factories/createScatterChart' {
  declare module.exports: any;
}

declare module '@devinit/charts/lib/factories/createTable' {
  declare module.exports: any;
}

declare module '@devinit/charts/lib/factories/createTitle' {
  declare module.exports: any;
}

declare module '@devinit/charts/lib/factories/createTreeChart' {
  declare module.exports: any;
}

declare module '@devinit/charts/lib/index' {
  declare module.exports: any;
}

declare module '@devinit/charts/schema/publish' {
  declare module.exports: any;
}

declare module '@devinit/charts/src/charts/area' {
  declare module.exports: any;
}

declare module '@devinit/charts/src/charts/bar' {
  declare module.exports: any;
}

declare module '@devinit/charts/src/charts/bubble' {
  declare module.exports: any;
}

declare module '@devinit/charts/src/charts/clustered-bar' {
  declare module.exports: any;
}

declare module '@devinit/charts/src/charts/compound-treemap' {
  declare module.exports: any;
}

declare module '@devinit/charts/src/charts/full-stacked-area' {
  declare module.exports: any;
}

declare module '@devinit/charts/src/charts/full-stacked-bar' {
  declare module.exports: any;
}

declare module '@devinit/charts/src/charts/line' {
  declare module.exports: any;
}

declare module '@devinit/charts/src/charts/partition' {
  declare module.exports: any;
}

declare module '@devinit/charts/src/charts/pie' {
  declare module.exports: any;
}

declare module '@devinit/charts/src/charts/stacked-area' {
  declare module.exports: any;
}

declare module '@devinit/charts/src/charts/stacked-bar' {
  declare module.exports: any;
}

declare module '@devinit/charts/src/charts/treemap' {
  declare module.exports: any;
}

declare module '@devinit/charts/src/factories/createAxis' {
  declare module.exports: any;
}

declare module '@devinit/charts/src/factories/createCircularChart' {
  declare module.exports: any;
}

declare module '@devinit/charts/src/factories/createDataset' {
  declare module.exports: any;
}

declare module '@devinit/charts/src/factories/createGrid' {
  declare module.exports: any;
}

declare module '@devinit/charts/src/factories/createLegend' {
  declare module.exports: any;
}

declare module '@devinit/charts/src/factories/createLinearChart' {
  declare module.exports: any;
}

declare module '@devinit/charts/src/factories/createScale' {
  declare module.exports: any;
}

declare module '@devinit/charts/src/factories/createScatterChart' {
  declare module.exports: any;
}

declare module '@devinit/charts/src/factories/createTable' {
  declare module.exports: any;
}

declare module '@devinit/charts/src/factories/createTitle' {
  declare module.exports: any;
}

declare module '@devinit/charts/src/factories/createTreeChart' {
  declare module.exports: any;
}

declare module '@devinit/charts/src/index' {
  declare module.exports: any;
}

declare module '@devinit/charts/test/createAxis.test' {
  declare module.exports: any;
}

declare module '@devinit/charts/test/createScale.test' {
  declare module.exports: any;
}

declare module '@devinit/charts/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module '@devinit/charts/dist/di-charts.min.js' {
  declare module.exports: $Exports<'@devinit/charts/dist/di-charts.min'>;
}
declare module '@devinit/charts/lib/charts/area.js' {
  declare module.exports: $Exports<'@devinit/charts/lib/charts/area'>;
}
declare module '@devinit/charts/lib/charts/bar.js' {
  declare module.exports: $Exports<'@devinit/charts/lib/charts/bar'>;
}
declare module '@devinit/charts/lib/charts/bubble.js' {
  declare module.exports: $Exports<'@devinit/charts/lib/charts/bubble'>;
}
declare module '@devinit/charts/lib/charts/clustered-bar.js' {
  declare module.exports: $Exports<'@devinit/charts/lib/charts/clustered-bar'>;
}
declare module '@devinit/charts/lib/charts/compound-treemap.js' {
  declare module.exports: $Exports<'@devinit/charts/lib/charts/compound-treemap'>;
}
declare module '@devinit/charts/lib/charts/full-stacked-area.js' {
  declare module.exports: $Exports<'@devinit/charts/lib/charts/full-stacked-area'>;
}
declare module '@devinit/charts/lib/charts/full-stacked-bar.js' {
  declare module.exports: $Exports<'@devinit/charts/lib/charts/full-stacked-bar'>;
}
declare module '@devinit/charts/lib/charts/line.js' {
  declare module.exports: $Exports<'@devinit/charts/lib/charts/line'>;
}
declare module '@devinit/charts/lib/charts/partition.js' {
  declare module.exports: $Exports<'@devinit/charts/lib/charts/partition'>;
}
declare module '@devinit/charts/lib/charts/pie.js' {
  declare module.exports: $Exports<'@devinit/charts/lib/charts/pie'>;
}
declare module '@devinit/charts/lib/charts/stacked-area.js' {
  declare module.exports: $Exports<'@devinit/charts/lib/charts/stacked-area'>;
}
declare module '@devinit/charts/lib/charts/stacked-bar.js' {
  declare module.exports: $Exports<'@devinit/charts/lib/charts/stacked-bar'>;
}
declare module '@devinit/charts/lib/charts/treemap.js' {
  declare module.exports: $Exports<'@devinit/charts/lib/charts/treemap'>;
}
declare module '@devinit/charts/lib/factories/createAxis.js' {
  declare module.exports: $Exports<'@devinit/charts/lib/factories/createAxis'>;
}
declare module '@devinit/charts/lib/factories/createCircularChart.js' {
  declare module.exports: $Exports<'@devinit/charts/lib/factories/createCircularChart'>;
}
declare module '@devinit/charts/lib/factories/createDataset.js' {
  declare module.exports: $Exports<'@devinit/charts/lib/factories/createDataset'>;
}
declare module '@devinit/charts/lib/factories/createGrid.js' {
  declare module.exports: $Exports<'@devinit/charts/lib/factories/createGrid'>;
}
declare module '@devinit/charts/lib/factories/createLegend.js' {
  declare module.exports: $Exports<'@devinit/charts/lib/factories/createLegend'>;
}
declare module '@devinit/charts/lib/factories/createLinearChart.js' {
  declare module.exports: $Exports<'@devinit/charts/lib/factories/createLinearChart'>;
}
declare module '@devinit/charts/lib/factories/createScale.js' {
  declare module.exports: $Exports<'@devinit/charts/lib/factories/createScale'>;
}
declare module '@devinit/charts/lib/factories/createScatterChart.js' {
  declare module.exports: $Exports<'@devinit/charts/lib/factories/createScatterChart'>;
}
declare module '@devinit/charts/lib/factories/createTable.js' {
  declare module.exports: $Exports<'@devinit/charts/lib/factories/createTable'>;
}
declare module '@devinit/charts/lib/factories/createTitle.js' {
  declare module.exports: $Exports<'@devinit/charts/lib/factories/createTitle'>;
}
declare module '@devinit/charts/lib/factories/createTreeChart.js' {
  declare module.exports: $Exports<'@devinit/charts/lib/factories/createTreeChart'>;
}
declare module '@devinit/charts/lib/index.js' {
  declare module.exports: $Exports<'@devinit/charts/lib/index'>;
}
declare module '@devinit/charts/schema/publish.js' {
  declare module.exports: $Exports<'@devinit/charts/schema/publish'>;
}
declare module '@devinit/charts/src/charts/area.js' {
  declare module.exports: $Exports<'@devinit/charts/src/charts/area'>;
}
declare module '@devinit/charts/src/charts/bar.js' {
  declare module.exports: $Exports<'@devinit/charts/src/charts/bar'>;
}
declare module '@devinit/charts/src/charts/bubble.js' {
  declare module.exports: $Exports<'@devinit/charts/src/charts/bubble'>;
}
declare module '@devinit/charts/src/charts/clustered-bar.js' {
  declare module.exports: $Exports<'@devinit/charts/src/charts/clustered-bar'>;
}
declare module '@devinit/charts/src/charts/compound-treemap.js' {
  declare module.exports: $Exports<'@devinit/charts/src/charts/compound-treemap'>;
}
declare module '@devinit/charts/src/charts/full-stacked-area.js' {
  declare module.exports: $Exports<'@devinit/charts/src/charts/full-stacked-area'>;
}
declare module '@devinit/charts/src/charts/full-stacked-bar.js' {
  declare module.exports: $Exports<'@devinit/charts/src/charts/full-stacked-bar'>;
}
declare module '@devinit/charts/src/charts/line.js' {
  declare module.exports: $Exports<'@devinit/charts/src/charts/line'>;
}
declare module '@devinit/charts/src/charts/partition.js' {
  declare module.exports: $Exports<'@devinit/charts/src/charts/partition'>;
}
declare module '@devinit/charts/src/charts/pie.js' {
  declare module.exports: $Exports<'@devinit/charts/src/charts/pie'>;
}
declare module '@devinit/charts/src/charts/stacked-area.js' {
  declare module.exports: $Exports<'@devinit/charts/src/charts/stacked-area'>;
}
declare module '@devinit/charts/src/charts/stacked-bar.js' {
  declare module.exports: $Exports<'@devinit/charts/src/charts/stacked-bar'>;
}
declare module '@devinit/charts/src/charts/treemap.js' {
  declare module.exports: $Exports<'@devinit/charts/src/charts/treemap'>;
}
declare module '@devinit/charts/src/factories/createAxis.js' {
  declare module.exports: $Exports<'@devinit/charts/src/factories/createAxis'>;
}
declare module '@devinit/charts/src/factories/createCircularChart.js' {
  declare module.exports: $Exports<'@devinit/charts/src/factories/createCircularChart'>;
}
declare module '@devinit/charts/src/factories/createDataset.js' {
  declare module.exports: $Exports<'@devinit/charts/src/factories/createDataset'>;
}
declare module '@devinit/charts/src/factories/createGrid.js' {
  declare module.exports: $Exports<'@devinit/charts/src/factories/createGrid'>;
}
declare module '@devinit/charts/src/factories/createLegend.js' {
  declare module.exports: $Exports<'@devinit/charts/src/factories/createLegend'>;
}
declare module '@devinit/charts/src/factories/createLinearChart.js' {
  declare module.exports: $Exports<'@devinit/charts/src/factories/createLinearChart'>;
}
declare module '@devinit/charts/src/factories/createScale.js' {
  declare module.exports: $Exports<'@devinit/charts/src/factories/createScale'>;
}
declare module '@devinit/charts/src/factories/createScatterChart.js' {
  declare module.exports: $Exports<'@devinit/charts/src/factories/createScatterChart'>;
}
declare module '@devinit/charts/src/factories/createTable.js' {
  declare module.exports: $Exports<'@devinit/charts/src/factories/createTable'>;
}
declare module '@devinit/charts/src/factories/createTitle.js' {
  declare module.exports: $Exports<'@devinit/charts/src/factories/createTitle'>;
}
declare module '@devinit/charts/src/factories/createTreeChart.js' {
  declare module.exports: $Exports<'@devinit/charts/src/factories/createTreeChart'>;
}
declare module '@devinit/charts/src/index.js' {
  declare module.exports: $Exports<'@devinit/charts/src/index'>;
}
declare module '@devinit/charts/test/createAxis.test.js' {
  declare module.exports: $Exports<'@devinit/charts/test/createAxis.test'>;
}
declare module '@devinit/charts/test/createScale.test.js' {
  declare module.exports: $Exports<'@devinit/charts/test/createScale.test'>;
}
declare module '@devinit/charts/webpack.config.js' {
  declare module.exports: $Exports<'@devinit/charts/webpack.config'>;
}
