// flow-typed signature: 4834d9ddc0aaeddb96b60b3403163610
// flow-typed version: <<STUB>>/redux-persist/constants_v4.8.1/flow_v0.51.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-persist/constants'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-persist/constants' {
  declare module.exports: any;
}
